"""
South Asian expansion of the built-in food list: everyday foods of Bangladesh first, then India,
Pakistan, Sri Lanka and Nepal. Appended to FOODS by foods_spec.py.

  F(...) - recipe estimate (src "local"): per 100 g of a typical home/restaurant recipe, computed from
           the ingredients (USDA / Bangladesh FCT 2013 / Indian FCT 2017 values) and rounded.
  T(...) - single ingredient (src "fct"): per 100 g from public food composition tables, rounded.

F(name, category, region, kcal, protein, carbs, fat, units, default, aliases)
  region   bd / in / pk / lk / np, sa = shared across South Asia, None = generic
  units    "plate=350,cup=160" - grams in ONE unit (ml for liquids that pass ml=density)
  default  "plate" (= 1 plate) or "piece*2"
  aliases  "|"-separated: other romanisations, Bangla script, Hindi/Urdu names
"""


def _units(spec):
    out = {}
    for part in spec.split(","):
        key, grams = part.split("=")
        out[key.strip()] = float(grams) if "." in grams else int(grams)
    return out


def _default(spec):
    unit, _, qty = spec.partition("*")
    q = float(qty) if qty else 1
    return (unit, int(q) if q == int(q) else q)


def F(name, cat, region, kcal, p, c, f, units, default, aliases, ml=None, src="local"):
    return dict(src=src, name=name, cat=cat, kcal=kcal, p=p, c=c, f=f, units=_units(units),
                aliases=[a.strip() for a in aliases.split("|") if a.strip()], default=_default(default),
                ml=ml, region=region)


def T(name, cat, region, kcal, p, c, f, units, default, aliases, ml=None):
    return F(name, cat, region, kcal, p, c, f, units, default, aliases, ml=ml, src="fct")


# Bangla-script names (and a few more spellings) for foods already in foods_spec.py.
EXTRA_ALIASES = {
    "White rice, cooked": ["ভাত", "chawal"],
    "Parboiled rice, cooked": ["সেদ্ধ চালের ভাত"],
    "Brown rice, cooked": ["লাল চালের ভাত"],
    "Sticky rice, cooked": ["বিন্নি চাল", "binni"],
    "Puffed rice (muri)": ["মুড়ি", "murmura", "mudi"],
    "Oats, dry": ["ওটস"],
    "Semolina (suji), dry": ["সুজি"],
    "Whole wheat flour (atta)": ["আটা"],
    "White flour (maida)": ["ময়দা"],
    "Instant noodles, dry": ["নুডলস"],
    "Roti / chapati": ["রুটি", "আটার রুটি", "chapathi", "phulka"],
    "Paratha": ["পরোটা", "parota", "porotha", "parantha"],
    "Naan": ["নান", "নান রুটি"],
    "White bread": ["পাউরুটি"],
    "Chicken breast, cooked": ["মুরগির মাংস"],
    "Chicken liver, cooked": ["মুরগির কলিজা"],
    "Duck, cooked": ["হাঁসের মাংস"],
    "Beef, cooked": ["গরুর মাংস", "gosht"],
    "Ground beef, cooked": ["কিমা"],
    "Goat / mutton, cooked": ["খাসির মাংস"],
    "Carp (rui, katla), cooked": ["রুই মাছ", "কাতলা মাছ"],
    "Catfish (pangas), cooked": ["পাঙ্গাস মাছ"],
    "Tilapia, cooked": ["তেলাপিয়া"],
    "Shrimp / prawns, cooked": ["চিংড়ি মাছ", "jhinga"],
    "Egg, boiled": ["সেদ্ধ ডিম", "ডিম", "anda"],
    "Egg, fried": ["ডিম ভাজা", "ডিম পোচ"],
    "Egg, scrambled / omelette": ["অমলেট", "mamlet"],
    "Milk, whole": ["দুধ", "doodh"],
    "Yogurt, plain (doi)": ["টক দই", "দই", "dahi"],
    "Ghee": ["ঘি"],
    "Butter": ["মাখন"],
    "Lentils, cooked (plain)": ["ডাল"],
    "Chickpeas, cooked": ["ছোলা", "chole"],
    "Mung beans, cooked": ["মুগ"],
    "Split peas, cooked": ["মটর ডাল", "খেসারি ডাল"],
    "Potato, boiled": ["আলু", "সেদ্ধ আলু"],
    "Sweet potato, boiled": ["মিষ্টি আলু"],
    "Onion, raw": ["পেঁয়াজ"],
    "Tomato, raw": ["টমেটো"],
    "Cucumber, raw": ["শসা"],
    "Carrot, raw": ["গাজর"],
    "Cabbage, raw": ["বাঁধাকপি"],
    "Cauliflower, cooked": ["ফুলকপি", "gobi"],
    "Spinach / leafy greens, cooked": ["শাক", "পালং শাক", "palak"],
    "Mustard greens, cooked": ["সরিষা শাক", "sarson"],
    "Eggplant, cooked": ["বেগুন"],
    "Okra, cooked": ["ঢেঁড়স"],
    "Pumpkin, cooked": ["মিষ্টি কুমড়া"],
    "Bitter gourd, cooked": ["করলা", "উচ্ছে"],
    "Bottle gourd, cooked": ["লাউ"],
    "Green peas, cooked": ["মটরশুঁটি", "matar"],
    "Sweet corn, cooked": ["ভুট্টা"],
    "Green chili": ["কাঁচা মরিচ", "mirchi"],
    "Garlic": ["রসুন"],
    "Ginger": ["আদা"],
    "Radish": ["মুলা", "mooli"],
    "Banana": ["কলা", "kela"],
    "Mango": ["আম"],
    "Apple": ["আপেল"],
    "Orange": ["কমলা", "মাল্টা"],
    "Lemon": ["লেবু", "nimbu"],
    "Papaya": ["পেঁপে"],
    "Guava": ["পেয়ারা", "amrood"],
    "Pineapple": ["আনারস"],
    "Watermelon": ["তরমুজ"],
    "Jackfruit": ["কাঁঠাল"],
    "Lychee": ["লিচু"],
    "Grapes": ["আঙুর"],
    "Pomegranate": ["ডালিম", "বেদানা"],
    "Dates": ["খেজুর"],
    "Star fruit": ["কামরাঙা"],
    "Sapodilla": ["সফেদা"],
    "Coconut, fresh": ["নারকেল"],
    "Coconut water": ["ডাবের পানি"],
    "Peanuts, roasted": ["চিনাবাদাম", "বাদাম"],
    "Almonds": ["কাঠবাদাম"],
    "Cashews": ["কাজু বাদাম"],
    "Soybean oil": ["সয়াবিন তেল"],
    "Mustard oil": ["সরিষার তেল"],
    "Sugar": ["চিনি"],
    "Brown sugar / jaggery": ["গুড়"],
    "Honey": ["মধু"],
    "Butter cookies / biscuits": ["বিস্কুট"],
    "Tea, black (no sugar)": ["রং চা", "লাল চা"],
    "Coffee, black": ["কফি"],
    "French fries": ["ফ্রেঞ্চ ফ্রাই"],
    "Fried chicken": ["চিকেন ফ্রাই"],
    "Fried rice": ["ফ্রাইড রাইস"],
    "Chicken chow mein": ["চাওমিন"],
    "Hamburger": ["বার্গার"],
    "Pizza, cheese": ["পিজা"],
    # Existing Bangladeshi dishes
    "Chicken biryani": ["চিকেন বিরিয়ানি", "বিরিয়ানি", "biriani"],
    "Kacchi biryani (mutton)": ["কাচ্চি বিরিয়ানি", "কাচ্চি"],
    "Beef tehari": ["তেহারি", "গরুর তেহারি"],
    "Morog polao": ["মোরগ পোলাও"],
    "Polao (plain)": ["পোলাও", "sada polao"],
    "Khichuri": ["খিচুড়ি"],
    "Panta bhat": ["পান্তা ভাত", "pakhala"],
    "Chicken curry": ["মুরগির ঝোল", "মুরগির মাংস ভুনা", "murgh"],
    "Beef curry": ["গরুর মাংস ভুনা", "gosht curry"],
    "Mutton curry": ["খাসির মাংস ভুনা", "mutton bhuna"],
    "Fish curry (rui / pangas)": ["মাছ", "মাছের ঝোল", "মাছের তরকারি", "katla", "rui mach"],
    "Hilsa, fried": ["ইলিশ মাছ ভাজা", "ইলিশ", "hilsha"],
    "Hilsa curry": ["সরষে ইলিশ", "ইলিশ মাছের ঝোল", "ilish bhuna"],
    "Small fish curry": ["ছোট মাছ", "মলা মাছ", "কাচকি"],
    "Shrimp curry": ["চিংড়ি ভুনা"],
    "Egg curry": ["ডিমের তরকারি", "ডিম ভুনা", "anda curry"],
    "Masoor dal": ["মসুর ডাল", "পাতলা ডাল"],
    "Thick dal (ghono dal)": ["ঘন ডাল"],
    "Mixed vegetable curry": ["সবজি", "তরকারি", "লাবড়া"],
    "Potato curry": ["আলুর তরকারি", "আলুর দম"],
    "Aloo bhorta": ["আলু ভর্তা", "ভর্তা"],
    "Begun bhorta": ["বেগুন ভর্তা"],
    "Shutki bhorta": ["শুঁটকি ভর্তা", "চ্যাপা শুঁটকি", "chepa shutki"],
    "Shak bhaji": ["শাক ভাজি", "পালং শাক ভাজি"],
    "Chicken roast": ["মুরগির রোস্ট", "রোস্ট"],
    "Shami kabab": ["শামি কাবাব", "shami kebab"],
    "Seekh kabab": ["শিক কাবাব", "seekh kebab"],
    "Chicken tikka / grilled": ["চিকেন টিক্কা", "গ্রিল চিকেন"],
    "Haleem": ["হালিম"],
    "Nihari": ["নেহারি"],
    "Luchi / puri": ["লুচি", "পুরি"],
    "Dal puri": ["ডাল পুরি", "ডালপুরি"],
    "Singara": ["সিঙ্গারা"],
    "Samosa": ["সমুচা", "samucha"],
    "Piyaju / pakora": ["পেঁয়াজু", "পিঁয়াজু", "pakoda", "bhajiya"],
    "Fuchka": ["ফুচকা", "puchka"],
    "Chotpoti": ["চটপটি"],
    "Jhalmuri": ["ঝালমুড়ি"],
    "Chanachur": ["চানাচুর", "namkeen"],
    "Chira (flattened rice), dry": ["চিড়া", "chida", "aval"],
    "Pitha (chitoi / bhapa)": ["পিঠা", "চিতই পিঠা"],
    "Payesh / kheer": ["পায়েস", "khir"],
    "Semai": ["সেমাই", "sevai"],
    "Rasgulla / roshogolla": ["রসগোল্লা", "মিষ্টি", "rosogolla", "roshgolla"],
    "Kalojam / gulab jamun": ["কালোজাম", "গোলাপজাম", "gulabjamun"],
    "Sandesh": ["সন্দেশ", "sondesh"],
    "Mishti doi": ["মিষ্টি দই", "bogra doi"],
    "Milk tea (cha)": ["দুধ চা", "চা", "chai"],
    "Milk coffee": ["দুধ কফি"],
    "Borhani": ["বোরহানি"],
    "Lassi, sweet": ["লাচ্ছি", "লাস্যি"],
    "Sugarcane juice": ["আখের রস", "ganne ka ras"],
}

SOUTH_ASIAN = [
    # ---- Rice dishes ----------------------------------------------------------------------------
    F("Beef biryani", "ricedish", "bd", 200, 9, 24, 7.5, "plate=350", "plate", "beef biriyani|gorur biryani|গরুর বিরিয়ানি|বিফ বিরিয়ানি"),
    F("Beef kacchi biryani", "ricedish", "bd", 215, 9.5, 23, 9.5, "plate=350", "plate", "beef kacchi|gorur kacchi|গরুর কাচ্চি"),
    F("Chicken kacchi biryani", "ricedish", "bd", 195, 9, 23, 7.5, "plate=350", "plate", "chicken kacchi|murgir kacchi|চিকেন কাচ্চি"),
    F("Kolkata mutton biryani (with potato)", "ricedish", "sa", 185, 7.5, 25, 6.3, "plate=350", "plate", "kolkata biryani|calcutta biryani|alu biryani|কলকাতা বিরিয়ানি"),
    F("Egg biryani", "ricedish", "sa", 175, 6, 25, 5.8, "plate=300", "plate", "dim biryani|anda biryani|ডিম বিরিয়ানি"),
    F("Vegetable biryani", "ricedish", "sa", 160, 3.5, 25, 5.3, "plate=300", "plate", "veg biryani|sobji biryani|সবজি বিরিয়ানি"),
    F("Prawn biryani", "ricedish", "sa", 175, 8, 24, 5.2, "plate=300", "plate", "chingri biryani|shrimp biryani|চিংড়ি বিরিয়ানি"),
    F("Hyderabadi chicken biryani", "ricedish", "in", 200, 9.5, 23, 7.8, "plate=350", "plate", "hyderabadi biryani|dum biryani|হায়দরাবাদি বিরিয়ানি"),
    F("Sindhi biryani", "ricedish", "pk", 195, 8.5, 24, 7.2, "plate=350", "plate", "karachi biryani|sindhi biriyani"),
    F("Chicken tehari", "ricedish", "bd", 185, 8, 24, 6.3, "plate=300", "plate", "murgir tehari|chicken tehri|চিকেন তেহারি"),
    F("Bhuna khichuri with beef", "ricedish", "bd", 175, 8, 19, 7.5, "plate=300", "plate", "bhuna khichuri|gorur mangsho khichuri|ভুনা খিচুড়ি|মাংস খিচুড়ি"),
    F("Chicken khichuri", "ricedish", "bd", 160, 7.5, 19, 6, "plate=300", "plate", "murgi khichuri|chicken khichdi|মুরগির খিচুড়ি"),
    F("Patla khichuri (soft, with vegetables)", "ricedish", "bd", 105, 3.5, 16, 3, "bowl=250,plate=300", "bowl", "patla khichuri|lentil rice porridge|dal khichdi|পাতলা খিচুড়ি|নরম খিচুড়ি"),
    F("Hilsa khichuri", "ricedish", "bd", 185, 8.5, 17, 9.2, "plate=300", "plate", "ilish khichuri|ইলিশ খিচুড়ি"),
    F("Hilsa polao", "ricedish", "bd", 200, 8, 22, 9, "plate=300", "plate", "ilish polao|ilish pulao|ইলিশ পোলাও"),
    F("Beef polao", "ricedish", "bd", 205, 9, 24, 8.2, "plate=300", "plate", "gorur mangsho polao|beef pulao|গরুর পোলাও"),
    F("Chicken fried rice", "ricedish", "bd", 175, 7.5, 24, 5.5, "plate=300", "plate", "chinese fried rice|চিকেন ফ্রাইড রাইস"),
    F("Egg fried rice", "ricedish", "sa", 165, 5, 25, 5, "plate=300", "plate", "dim fried rice|এগ ফ্রাইড রাইস"),
    F("Vegetable fried rice", "ricedish", "sa", 155, 3.5, 25, 4.5, "plate=300", "plate", "veg fried rice|ভেজিটেবল ফ্রাইড রাইস"),
    F("Prawn fried rice", "ricedish", "bd", 165, 7, 24, 4.6, "plate=300", "plate", "shrimp fried rice|chingri fried rice|প্রন ফ্রাইড রাইস"),
    F("Vegetable chow mein", "ricedish", "sa", 150, 4, 22, 5, "plate=300", "plate", "veg chowmein|vegetable noodles|ভেজিটেবল চাওমিন"),
    F("Jeera rice", "ricedish", "in", 160, 3, 28, 4, "plate=250,cup=160", "plate", "cumin rice|jira rice|জিরা রাইস"),
    F("Vegetable pulao", "ricedish", "in", 150, 3.2, 25, 4.2, "plate=250,cup=160", "plate", "veg pulao|veg polao|সবজি পোলাও"),
    F("Yakhni pulao (mutton)", "ricedish", "pk", 190, 8, 24, 7, "plate=300", "plate", "yakhni pulao|mutton pulao|gosht pulao"),
    F("Kabuli pulao", "ricedish", "pk", 210, 8, 28, 7.5, "plate=300", "plate", "afghani pulao|kabuli palaw"),
    F("Lemon rice", "ricedish", "in", 165, 3, 27, 5, "plate=250,cup=160", "plate", "chitranna|nimbu chawal"),
    F("Curd rice", "ricedish", "in", 120, 3.5, 18, 3.8, "plate=250,bowl=200", "bowl", "thayir sadam|dahi chawal|doi bhat|দই ভাত"),
    F("Tamarind rice", "ricedish", "in", 180, 3.2, 28, 6.2, "plate=250", "plate", "puliyogare|puliyodharai|imli rice"),
    F("Bisi bele bath", "ricedish", "in", 140, 4.5, 20, 4.7, "plate=300,bowl=250", "plate", "bisibelebath|sambar rice"),
    F("Ven pongal", "ricedish", "in", 150, 4.5, 20, 5.8, "plate=250,bowl=200", "plate", "pongal|khara pongal"),
    F("Rajma chawal", "ricedish", "in", 140, 5, 24, 2.8, "plate=350", "plate", "rajma rice|rajma chaval"),
    F("Dal bhat (Nepali set)", "ricedish", "np", 115, 4, 21, 1.7, "plate=450", "plate", "dal bhat|daal bhaat|dal bhat tarkari"),
    F("Lamprais", "ricedish", "lk", 195, 8, 22, 8.5, "plate=450", "plate", "lump rice|lamprai"),
    F("Sri Lankan yellow rice", "ricedish", "lk", 175, 3, 28, 5.8, "plate=250", "plate", "kaha bath|yellow rice"),
    F("Kiribath (milk rice)", "ricedish", "lk", 165, 3, 26, 5.5, "piece=80", "piece*2", "kiribath|milk rice|kiri bath"),
    T("Basmati rice, cooked", "grain", None, 120, 3.5, 25.2, 0.4, "plate=250,cup=160", "plate", "basmati|বাসমতি চালের ভাত|basmati chawal"),
    T("Aromatic rice (chinigura / kalijira), cooked", "grain", "bd", 128, 2.7, 28.5, 0.4, "plate=250,cup=160", "plate", "chinigura|kalijira|polao chal|চিনিগুড়া|কালিজিরা চাল"),
    T("Raw rice (chal)", "grain", None, 360, 6.8, 79, 0.6, "cup=185", "cup*0.5", "chal|uncooked white rice|চাল|chawal raw"),

    # ---- Grains, flours, cereals -----------------------------------------------------------------
    T("Popped rice (khoi)", "grain", "bd", 385, 7, 87, 0.6, "cup=12,handful=10", "cup", "khoi|lai|kheel|খই"),
    T("Rice flour", "grain", "sa", 360, 6, 80, 1.4, "cup=160,tbsp=10", "cup*0.5", "chaler gura|chawal ka atta|চালের গুঁড়া"),
    T("Gram flour (besan)", "grain", "sa", 380, 22, 58, 6.7, "cup=92,tbsp=8", "tbsp*2", "besan|beshon|chickpea flour|বেসন"),
    T("Sattu (roasted gram flour)", "grain", "in", 400, 20.6, 65, 5.6, "tbsp=10,cup=100", "tbsp*3", "sattu|chhatu|ছাতু"),
    T("Finger millet flour (ragi)", "grain", "in", 328, 7.3, 72, 1.3, "cup=120,tbsp=8", "cup*0.5", "ragi|nachni|mandua"),
    T("Sorghum flour (jowar)", "grain", "in", 345, 10.4, 70.7, 1.9, "cup=120,tbsp=8", "cup*0.5", "jowar|jowari|jonar ata"),
    T("Pearl millet flour (bajra)", "grain", "in", 361, 11.6, 67.5, 5, "cup=120,tbsp=8", "cup*0.5", "bajra|bajri|kaon"),
    T("Maize flour (makki atta)", "grain", "in", 365, 8.1, 76.9, 3.6, "cup=120,tbsp=8", "cup*0.5", "makki atta|cornmeal|bhuttar ata|ভুট্টার আটা"),
    T("Sago pearls (sabudana), dry", "grain", "in", 355, 0.2, 88.7, 0, "cup=150,tbsp=10", "cup*0.5", "sabudana|sagu|sago|সাগু"),
    T("Broken wheat (dalia), cooked", "grain", "in", 85, 3.1, 18.6, 0.2, "bowl=200,cup=180", "bowl", "dalia|daliya|lapsi|bulgur|ভাঙা গম"),
    T("Barley, cooked", "grain", None, 123, 2.3, 28.2, 0.4, "cup=157,bowl=200", "cup", "jau|job|barley|যব"),
    T("Vermicelli (semai), dry", "grain", "sa", 355, 12, 73, 1.5, "cup=60,handful=25", "handful", "semai dry|seviyan|সেমাই (শুকনা)"),
    F("Lachha semai, dry (fried)", "dessert", "bd", 500, 8, 60, 25, "cup=50,handful=25", "handful", "lachcha semai|laccha shemai|লাচ্ছা সেমাই"),
    F("Lachha semai, cooked with milk", "dessert", "bd", 230, 5, 30, 10, "bowl=150", "bowl", "lachha shemai|dudh semai|লাচ্ছা সেমাই রান্না"),
    T("Quinoa, cooked", "grain", None, 120, 4.4, 21.3, 1.9, "cup=185", "cup", "quinoa|কিনোয়া"),
    F("Muesli", "grain", None, 360, 10, 66, 6, "cup=85,bowl=60", "bowl", "musli|granola"),
    T("Cornflour (corn starch)", "grain", None, 381, 0.3, 91, 0.1, "tbsp=8", "tbsp", "corn starch|cornflour|কর্নফ্লাওয়ার"),
    F("Dhindo", "grain", "np", 110, 3, 23, 0.6, "plate=300,bowl=250", "plate", "dhido|buckwheat dhindo|millet dhindo"),

    # ---- Breads ----------------------------------------------------------------------------------
    F("Lachha paratha", "bread", "sa", 320, 6.5, 42, 14, "piece=80", "piece", "lachha porota|laccha paratha|layered paratha|লাচ্ছা পরোটা"),
    F("Aloo paratha", "bread", "sa", 230, 5, 32, 9.3, "piece=120", "piece", "alu porota|aloo parantha|potato paratha|আলু পরোটা"),
    F("Mughlai paratha", "bread", "bd", 280, 10, 25, 15.5, "piece=200", "piece", "moglai porota|mughlai porota|মোগলাই পরোটা"),
    F("Egg paratha (dim porota)", "bread", "bd", 290, 9, 30, 15, "piece=130", "piece", "dim porota|anda paratha|egg porota|ডিম পরোটা"),
    F("Keema paratha", "bread", "sa", 280, 11, 30, 13, "piece=150", "piece", "kima porota|qeema paratha|কিমা পরোটা"),
    F("Paneer paratha", "bread", "in", 260, 9, 30, 11.5, "piece=130", "piece", "paneer parantha|পনির পরোটা"),
    F("Gobi paratha", "bread", "in", 230, 5, 31, 9.5, "piece=120", "piece", "gobhi paratha|cauliflower paratha|ফুলকপি পরোটা"),
    F("Tandoori roti", "bread", "sa", 270, 9, 52, 2.5, "piece=60", "piece*2", "tandoor roti|tandoori ruti|তন্দুরি রুটি"),
    F("Butter naan", "bread", "sa", 310, 8.5, 47, 9.8, "piece=100", "piece", "butter nan|বাটার নান"),
    F("Garlic naan", "bread", "sa", 300, 8.5, 47, 8.8, "piece=100", "piece", "garlic nan|রসুন নান|গার্লিক নান"),
    F("Cheese naan", "bread", "sa", 310, 11, 40, 12, "piece=130", "piece", "cheese nan|চিজ নান"),
    F("Peshawari naan", "bread", "pk", 330, 8, 50, 11, "piece=130", "piece", "peshwari nan|sweet naan"),
    F("Roghni naan", "bread", "pk", 320, 9, 48, 10, "piece=110", "piece", "roghani naan|rogni nan"),
    F("Kulcha", "bread", "in", 290, 8, 50, 6.5, "piece=80", "piece", "plain kulcha|kulche|কুলচা"),
    F("Amritsari kulcha (stuffed)", "bread", "in", 260, 6, 38, 9.5, "piece=130", "piece", "aloo kulcha|stuffed kulcha"),
    F("Bhatura", "bread", "in", 330, 7, 45, 13.5, "piece=70", "piece*2", "bhature|batura|ভাটুরা"),
    F("Bakarkhani", "bread", "bd", 440, 8, 55, 21, "piece=25", "piece*2", "bakorkhani|bakarkhani ruti|বাকরখানি"),
    F("Rice flour roti (chaler ruti)", "bread", "bd", 200, 3.2, 44, 0.8, "piece=50", "piece*2", "chaler ruti|chal er ruti|akki roti|চালের রুটি"),
    F("Makki di roti", "bread", "in", 260, 5.5, 44, 7, "piece=70", "piece*2", "makki roti|makai roti|corn roti"),
    F("Bajra roti", "bread", "in", 290, 8.5, 52, 5.3, "piece=50", "piece*2", "bajri rotla|bajra rotla|millet roti"),
    F("Jowar bhakri", "bread", "in", 270, 8, 55, 2.2, "piece=50", "piece*2", "jowar roti|jolada rotti|bhakri"),
    F("Thepla", "bread", "in", 300, 8, 42, 11, "piece=40", "piece*2", "methi thepla|theplu"),
    F("Missi roti", "bread", "in", 290, 11, 45, 7, "piece=60", "piece*2", "besan roti|missi"),
    F("Rumali roti", "bread", "sa", 270, 8, 50, 4, "piece=50", "piece*2", "roomali roti|rumali ruti|রুমালি রুটি"),
    F("Sheermal", "bread", "pk", 360, 8.5, 52, 13, "piece=80", "piece", "shirmal|sheer mal|শিরমাল"),
    F("Taftan", "bread", "pk", 320, 9, 52, 8.5, "piece=100", "piece", "taftoon"),
    F("Kochuri (Bengali)", "bread", "sa", 340, 7, 40, 17, "piece=35", "piece*3", "koraishutir kochuri|hing kochuri|kachori bengali|কচুরি|কড়াইশুঁটির কচুরি"),
    F("Radhaballavi", "bread", "sa", 340, 8, 40, 16.5, "piece=40", "piece*3", "radhaballabhi|radha bollobi|রাধাবল্লভী"),
    F("Dosa, plain", "bread", "in", 165, 4, 27, 4.5, "piece=80", "piece*2", "dosai|dosha|plain dosa|ধোসা"),
    F("Masala dosa", "bread", "in", 180, 3.8, 26, 6.8, "piece=180", "piece", "masala dosai|মাসালা ধোসা"),
    F("Rava dosa", "bread", "in", 210, 4.5, 30, 8, "piece=90", "piece*2", "rava dosai|suji dosa"),
    F("Onion uttapam", "bread", "in", 160, 4, 24, 5.2, "piece=150", "piece", "uttapam|uthappam|oothappam"),
    F("Idli", "bread", "in", 128, 4, 26, 0.8, "piece=40", "piece*3", "idly|iddli|ইডলি"),
    F("Rava idli", "bread", "in", 160, 4.5, 25, 4.8, "piece=50", "piece*2", "suji idli|rava idly"),
    F("Appam", "bread", "in", 150, 2.5, 28, 3.2, "piece=60", "piece*2", "palappam|vellayappam|hoppers"),
    F("String hoppers (idiyappam)", "bread", "lk", 150, 2.7, 33, 0.6, "piece=25", "piece*5", "idiyappam|indiappa|string hopper|noolappam"),
    F("Egg hopper", "bread", "lk", 180, 6, 22, 7.5, "piece=100", "piece", "biththara appa|egg appa|egg appam"),
    F("Pol roti", "bread", "lk", 300, 5.5, 38, 14, "piece=70", "piece*2", "coconut roti|pol rotti"),
    F("Kerala parotta", "bread", "in", 330, 7, 45, 13.5, "piece=90", "piece", "parotta|porotta|malabar paratha|barotta"),
    F("Chicken kottu roti", "bread", "lk", 200, 8, 22, 8.8, "plate=350", "plate", "kottu|koththu|kottu roti"),
    F("Pesarattu", "bread", "in", 170, 8, 24, 4.7, "piece=100", "piece*2", "moong dosa|green gram dosa"),
    F("Neer dosa", "bread", "in", 150, 2.5, 30, 2, "piece=50", "piece*3", "neer dose|rice crepe"),
    F("Puttu", "bread", "in", 170, 3, 35, 2, "piece=120", "piece", "pittu|puttu kadala"),
    F("Sel roti", "bread", "np", 360, 5, 52, 15, "piece=50", "piece*2", "selroti|sel rotti"),
    F("Pav (bread roll)", "bread", "in", 290, 9, 50, 6, "piece=40", "piece*2", "pav|pao|ladi pav|dinner roll"),
    F("Sweet bun (bakery)", "bread", "bd", 300, 8, 52, 6.5, "piece=60", "piece", "bon ruti|bun|bonruti|বন রুটি|বান"),
    F("Bara (lentil patty)", "bread", "np", 190, 9, 20, 8, "piece=60", "piece*2", "wo|woh|bara nepali"),
    F("Chatamari", "bread", "np", 180, 8, 22, 6.6, "piece=120", "piece", "chatamari|newari pizza"),
    F("Litti chokha", "bread", "in", 250, 7, 36, 8.8, "piece=70,plate=280", "piece*2", "litti|litti chokha|baati chokha"),

    # ---- Dals, beans, chickpeas -----------------------------------------------------------------
    F("Moong dal (Bengali)", "legume", "bd", 95, 5.5, 13, 2.4, "bowl=200,cup=240", "bowl", "mug dal|moog dal|muger dal|মুগ ডাল|মুগের ডাল"),
    F("Mashkalai dal", "legume", "bd", 100, 5.5, 12, 3.3, "bowl=200,cup=240", "bowl", "mashkalai|biulir dal|urad dal|মাষকলাই ডাল|বিউলির ডাল"),
    F("Cholar dal (Bengali, with coconut)", "legume", "bd", 150, 6.5, 18, 5.8, "bowl=200", "bowl", "cholar dal|chana dal|ছোলার ডাল"),
    F("Dal tadka / dal fry", "legume", "sa", 110, 5.5, 13, 4, "bowl=200,cup=240", "bowl", "dal fry|tadka dal|toor dal|arhar dal|ডাল তড়কা|ডাল ফ্রাই"),
    F("Dal makhani", "legume", "in", 150, 5.5, 14, 8, "bowl=200", "bowl", "dal makhni|maa ki dal|ডাল মাখানি"),
    F("Sambar", "legume", "in", 70, 3, 9, 2.4, "bowl=200,cup=240", "bowl", "sambhar|saambar|সাম্বার"),
    F("Rasam", "legume", "in", 35, 1.2, 5, 1.2, "bowl=200,glass=200", "bowl", "saaru|chaaru|pepper rasam"),
    T("Pigeon peas (toor dal), cooked", "legume", "in", 121, 6.8, 23.3, 0.4, "bowl=200,cup=168", "bowl", "toor|tuvar|arhar|orhor dal|অড়হর ডাল"),
    F("Chana masala / chole", "legume", "sa", 150, 6.5, 19, 5.3, "bowl=200,cup=200", "bowl", "chole masala|chholey|chana curry|ছোলা মাসালা"),
    F("Rajma masala", "legume", "in", 125, 5.5, 16, 4.3, "bowl=200", "bowl", "rajma curry|kidney bean curry|রাজমা"),
    F("Ghugni", "legume", "bd", 125, 6, 16, 4, "bowl=200,cup=200", "bowl", "ghugni chaat|dried peas curry|motor ghugni|ঘুগনি"),
    F("Chola bhuna (iftar chickpeas)", "legume", "bd", 170, 7.5, 20, 6.5, "cup=150,bowl=200", "cup", "boot bhuna|chola bhuna|iftar chola|ছোলা ভুনা|বুট ভুনা"),
    F("Mixed dal (panchmel)", "legume", "in", 110, 6, 14, 3.4, "bowl=200", "bowl", "panchmel dal|mix dal|মিক্সড ডাল"),
    F("Dal gosht", "curry", "pk", 150, 10, 10, 8, "bowl=200", "bowl", "daal gosht|dal meat|ডাল গোশত"),
    T("Black chickpeas (kala chana), cooked", "legume", "sa", 165, 8.9, 27, 2.6, "cup=164,bowl=200", "cup", "kala chana|kalo chola|desi chana|কালো ছোলা"),
    T("Black gram (urad), cooked", "legume", "sa", 105, 7.5, 18, 0.6, "cup=180,bowl=200", "cup", "urad|mashkalai boiled|kali dal|মাষকলাই"),
    T("Red lentils (masoor), dry", "legume", "sa", 358, 24.6, 60, 2.2, "cup=192,tbsp=12", "cup*0.25", "masoor dry|musur dal raw|মসুর ডাল (কাঁচা)"),
    T("Mung dal, dry", "legume", "sa", 348, 24, 60, 1.2, "cup=200,tbsp=12", "cup*0.25", "moong dal raw|mug dal dry|মুগ ডাল (কাঁচা)"),
    T("Chana dal, dry", "legume", "sa", 370, 20.5, 61, 5.6, "cup=200,tbsp=12", "cup*0.25", "bengal gram|chana dal raw|ছোলার ডাল (কাঁচা)"),
    T("Soya chunks, dry", "legume", "sa", 345, 52, 33, 0.5, "cup=50,handful=20", "handful", "meal maker|nutrela|soybean bori|সয়াবিন বড়ি"),
    F("Soya chunk curry", "curry", "sa", 120, 9, 9, 5.3, "bowl=150", "bowl", "soyabean curry|meal maker curry|সয়াবিনের তরকারি"),
    T("Black-eyed peas (lobia), cooked", "legume", "in", 116, 7.7, 20.8, 0.5, "cup=170,bowl=200", "cup", "lobia|chawli|barbati beans|cowpeas"),
    T("Mung bean sprouts", "legume", "sa", 30, 3, 5.9, 0.2, "cup=104,handful=30", "cup*0.5", "sprouts|ankurito mug|moong sprouts|অঙ্কুরিত মুগ"),
    T("Roasted chickpeas (chola bhaja)", "legume", "sa", 369, 22, 58, 5.2, "handful=30,cup=100", "handful", "bhuna chana|bhuna chola|chola bhaja|ছোলা ভাজা"),
    F("Parippu (Sri Lankan dhal curry)", "legume", "lk", 120, 5.5, 13, 5.3, "bowl=200", "bowl", "dhal curry|parippu|lentil curry coconut"),
    F("Nepali black lentil dal", "legume", "np", 100, 6, 13, 2.7, "bowl=200", "bowl", "kalo dal|maas ko dal|black dal"),
    F("Kwati (mixed bean soup)", "legume", "np", 110, 7, 16, 2, "bowl=250", "bowl", "kwati|quati|nine bean soup"),
    F("Dal bora (lentil fritters)", "snack", "bd", 300, 12, 25, 17, "piece=20", "piece*3", "daler bora|dal vada|ডালের বড়া"),
    F("Kadhi pakora", "curry", "in", 105, 3.5, 9, 6, "bowl=200", "bowl", "kadhi|karhi|punjabi kadhi"),

    # ---- Bhortas, chutneys, pickles --------------------------------------------------------------
    F("Dal bhorta", "curry", "bd", 170, 8, 18, 7.5, "scoop=60,tbsp=15", "scoop", "daler bhorta|lentil mash|ডাল ভর্তা"),
    F("Egg bhorta (dim bhorta)", "egg", "bd", 180, 10, 6, 13, "scoop=60", "scoop", "dim bhorta|egg bhorta|ডিম ভর্তা"),
    F("Chingri bhorta", "curry", "bd", 170, 15, 4, 10.5, "scoop=50", "scoop", "shrimp bhorta|chingri vorta|চিংড়ি ভর্তা"),
    F("Tomato bhorta", "curry", "bd", 70, 1.2, 5, 5, "scoop=60", "scoop", "tomato vorta|টমেটো ভর্তা"),
    F("Kalojira bhorta", "curry", "bd", 330, 12, 20, 22, "tbsp=12", "tbsp*2", "kalijira bhorta|nigella bhorta|কালোজিরা ভর্তা"),
    F("Shim bhorta", "curry", "bd", 110, 4, 9, 6.5, "scoop=60", "scoop", "sheem bhorta|bean bhorta|শিম ভর্তা"),
    F("Kacha kola bhorta", "curry", "bd", 125, 1.3, 21, 4, "scoop=70", "scoop", "green banana bhorta|kanchkola bhorta|কাঁচা কলা ভর্তা"),
    F("Dried chilli bhorta", "curry", "bd", 240, 6, 20, 15.5, "tbsp=10", "tbsp*2", "shukna morich bhorta|morich bhorta|শুকনা মরিচ ভর্তা"),
    F("Taki fish bhorta", "curry", "bd", 170, 16, 4, 10, "scoop=50", "scoop", "taki mach bhorta|taki bhorta|টাকি মাছ ভর্তা"),
    F("Fish bhorta", "curry", "bd", 175, 15, 3, 11.5, "scoop=50", "scoop", "macher bhorta|rui bhorta|ilish bhorta|মাছ ভর্তা"),
    F("Posto bata (poppy seed paste)", "curry", "sa", 410, 15, 20, 30, "tbsp=15", "tbsp*2", "posto|poppy paste|পোস্ত বাটা"),
    F("Coconut chutney", "other", "in", 200, 2.5, 8, 18, "tbsp=15,serving=50", "serving", "nariyal chutney|thengai chutney|নারকেলের চাটনি"),
    F("Pol sambol", "other", "lk", 290, 3, 12, 26, "tbsp=10", "tbsp*2", "coconut sambol|pol sambola"),
    F("Gotu kola sambol", "leafy", "lk", 110, 2.5, 7, 8, "serving=50", "serving", "gotukola|centella sambol"),
    F("Mint chutney", "other", "sa", 60, 2.5, 8, 2, "tbsp=15", "tbsp*2", "pudina chutney|hari chutney|green chutney|পুদিনার চাটনি"),
    F("Tamarind chutney (sweet)", "other", "sa", 230, 1, 56, 0.2, "tbsp=20", "tbsp", "tetul chutney|imli chutney|saunth|তেঁতুলের চাটনি|টক"),
    F("Tomato chutney (Bengali, sweet)", "other", "bd", 150, 1, 33, 1.7, "tbsp=20", "tbsp*2", "tomato chatni|tomatar chutney|টমেটোর চাটনি"),
    F("Mango pickle", "other", "sa", 200, 1.5, 14, 15.5, "tbsp=15", "tbsp", "aamer achar|aam ka achar|achar|আমের আচার|আচার"),
    F("Olive pickle (jolpai achar)", "other", "bd", 220, 0.8, 50, 2, "tbsp=20", "tbsp", "jolpai achar|jolpai|জলপাইয়ের আচার"),
    F("Jujube pickle (boroi achar)", "other", "bd", 250, 1, 58, 2, "tbsp=20", "tbsp", "boroi achar|kuler achar|বরই আচার"),
    F("Raita", "dairy", "sa", 60, 3, 5, 3, "bowl=100,tbsp=15", "bowl", "cucumber raita|boondi raita|রায়তা"),
    F("Kasundi (mustard sauce)", "other", "bd", 150, 5, 10, 10, "tbsp=16", "tbsp", "kashundi|mustard sauce|কাসুন্দি"),
    F("Mustard paste (shorshe bata)", "other", "bd", 260, 13, 14, 18, "tbsp=15", "tbsp", "shorshe bata|sorisha bata|সরিষা বাটা"),
    F("Nepali aloo achar", "vegetable", "np", 150, 2, 16, 8.7, "bowl=100", "bowl", "aloo ko achar|alu achar"),
    F("Lunu miris", "other", "lk", 120, 2, 12, 7.2, "tbsp=10", "tbsp", "lunu miris sambol|chilli onion sambol"),

    # ---- Vegetable dishes ----------------------------------------------------------------------
    F("Aloo bhaji (potato stir-fry)", "vegetable", "bd", 150, 2, 18, 7.8, "bowl=150,cup=150", "bowl", "alu bhaji|alu bhaja|aloo sabzi|আলু ভাজি"),
    F("Begun bhaja (fried eggplant)", "vegetable", "bd", 150, 1.5, 9, 12, "piece=30", "piece*2", "begun bhaja|baingan fry|বেগুন ভাজা"),
    F("Lau torkari (bottle gourd curry)", "vegetable", "bd", 55, 1, 4.5, 3.7, "bowl=150", "bowl", "lau ghonto|lauki sabzi|লাউ তরকারি|লাউ ঘণ্ট"),
    F("Lau chingri", "curry", "bd", 75, 4.5, 4, 4.5, "bowl=150", "bowl", "lau diye chingri|লাউ চিংড়ি"),
    F("Potol bhaji (pointed gourd)", "vegetable", "bd", 90, 1.5, 7, 6.3, "bowl=150", "bowl", "potol bhaja|parwal sabzi|পটল ভাজি"),
    F("Potol dolma (stuffed)", "vegetable", "bd", 150, 6, 8, 10.5, "piece=50", "piece*2", "potoler dolma|potol dorma|পটলের দোলমা"),
    F("Jhinga torkari (ridge gourd)", "vegetable", "bd", 60, 1.2, 5, 4, "bowl=150", "bowl", "jhinge|turai sabzi|dhundul|ঝিঙা তরকারি|ধুন্দুল"),
    F("Kakrol bhaji (spiny gourd)", "vegetable", "bd", 95, 2, 7, 6.5, "bowl=150", "bowl", "kakrol bhaja|kantola|kakrol|কাঁকরোল ভাজি"),
    F("Dherosh bhaji (okra stir-fry)", "vegetable", "bd", 100, 2, 8, 6.8, "bowl=150", "bowl", "bhindi fry|dherosh bhaja|ঢেঁড়স ভাজি"),
    F("Korola bhaji (bitter gourd fry)", "vegetable", "bd", 100, 1.5, 7, 7.5, "bowl=100", "bowl", "karela fry|uchche bhaja|করলা ভাজি"),
    F("Chichinga torkari (snake gourd)", "vegetable", "bd", 60, 1, 5, 4, "bowl=150", "bowl", "chichinga|chichinge|চিচিঙ্গা"),
    F("Pumpkin bhaji (mishti kumra)", "vegetable", "bd", 85, 1, 9, 5, "bowl=150", "bowl", "kumra bhaji|kaddu sabzi|মিষ্টি কুমড়া ভাজি"),
    F("Cauliflower curry (fulkopi torkari)", "vegetable", "bd", 85, 2.2, 8, 5, "bowl=150", "bowl", "fulkopi torkari|phulkopir dalna|ফুলকপির তরকারি"),
    F("Cabbage bhaji (badhakopi)", "vegetable", "bd", 75, 1.5, 7, 4.6, "bowl=150", "bowl", "badhakopi bhaji|bandhakopir ghonto|patta gobhi|বাঁধাকপি ভাজি"),
    F("Shim bhaji (flat bean stir-fry)", "vegetable", "bd", 80, 2.5, 7, 4.8, "bowl=150", "bowl", "sheem bhaji|seem|শিম ভাজি"),
    F("Mula torkari (radish curry)", "vegetable", "bd", 55, 1, 4.5, 3.7, "bowl=150", "bowl", "mulo|mooli sabzi|মুলার তরকারি"),
    F("Kacha kolar torkari (green banana curry)", "vegetable", "bd", 110, 1.3, 17, 4.2, "bowl=150", "bowl", "kanchkola|green banana curry|raw banana|কাঁচা কলার তরকারি"),
    F("Kochur loti (taro stolon)", "vegetable", "bd", 90, 4, 6, 5.5, "bowl=150", "bowl", "kochur lati|loti chingri|কচুর লতি"),
    F("Kochu shak (taro leaves)", "leafy", "bd", 90, 3, 7, 5.5, "bowl=120", "bowl", "kochu pata|arbi leaves|কচু শাক"),
    F("Mochar ghonto (banana flower)", "vegetable", "bd", 110, 2.5, 10, 6.8, "bowl=150", "bowl", "mocha|banana blossom|মোচার ঘণ্ট"),
    F("Echor (green jackfruit curry)", "vegetable", "bd", 115, 2.5, 14, 5.5, "bowl=150", "bowl", "enchor|kathal sabzi|kacha kathal|এঁচোড়"),
    F("Shukto", "vegetable", "bd", 80, 2, 8, 4.5, "bowl=150", "bowl", "sukto|shukta|শুক্তো"),
    F("Chorchori (mixed vegetables)", "vegetable", "bd", 90, 2, 9, 5.2, "bowl=150", "bowl", "chochori|chorchori|চচ্চড়ি"),
    F("Mixed vegetable bhaji", "vegetable", "bd", 95, 2, 9, 5.8, "bowl=150", "bowl", "sobji bhaji|shobji bhaji|vegetable bhaji|সবজি ভাজি"),
    F("Aloo posto", "vegetable", "bd", 150, 3, 15, 8.8, "bowl=150", "bowl", "alu posto|potato poppy seed|আলু পোস্ত"),
    F("Dhokar dalna", "curry", "bd", 170, 7, 16, 8.8, "bowl=150", "bowl", "dhoka|lentil cake curry|ধোকার ডালনা"),
    F("Chhanar dalna", "curry", "bd", 170, 8, 9, 11.5, "bowl=150", "bowl", "chanar dalna|paneer curry bengali|ছানার ডালনা"),
    F("Green papaya curry", "vegetable", "bd", 60, 0.8, 7, 3.3, "bowl=150", "bowl", "kacha pepe|pepe torkari|কাঁচা পেঁপের তরকারি"),
    F("Drumstick curry (shojne data)", "vegetable", "bd", 70, 2.5, 6, 4, "bowl=150", "bowl", "sojne data|sajna|drumstick|সজনে ডাটা"),
    F("Taro root curry (mukhi kochu)", "vegetable", "bd", 110, 1.8, 15, 4.8, "bowl=150", "bowl", "mukhi kochu|arbi sabzi|kochu|মুখী কচু"),
    F("Palak paneer", "curry", "in", 145, 6.5, 5, 11, "bowl=200", "bowl", "saag paneer|palong paneer|পালক পনির"),
    F("Paneer butter masala", "curry", "in", 230, 8, 8, 18.5, "bowl=200", "bowl", "paneer makhani|butter paneer|পনির বাটার মাসালা"),
    F("Kadai paneer", "curry", "in", 200, 9, 7, 15, "bowl=200", "bowl", "karahi paneer|kadhai paneer"),
    F("Matar paneer", "curry", "in", 170, 8, 9, 11.5, "bowl=200", "bowl", "mutter paneer|peas paneer"),
    F("Shahi paneer", "curry", "in", 240, 8.5, 8, 19.5, "bowl=200", "bowl", "paneer korma"),
    F("Paneer tikka", "dairy", "in", 250, 15, 6, 18.5, "piece=30", "piece*4", "paneer tikka|পনির টিক্কা"),
    F("Aloo gobi", "vegetable", "in", 100, 2.2, 11, 5.3, "bowl=150", "bowl", "alu gobi|aloo gobhi|আলু ফুলকপি"),
    F("Aloo matar", "vegetable", "in", 110, 3, 13, 5, "bowl=150", "bowl", "alu motor|aloo mutter|আলু মটর"),
    F("Bhindi masala", "vegetable", "in", 110, 2.2, 9, 7.3, "bowl=150", "bowl", "bhindi do pyaza|okra masala"),
    F("Sarson da saag", "leafy", "in", 110, 3.5, 7, 7.5, "bowl=150", "bowl", "sarson ka saag|saag|mustard saag"),
    F("Malai kofta", "curry", "in", 220, 5.5, 12, 16.5, "bowl=200", "bowl", "malai kofta curry|মালাই কোফতা"),
    F("Navratan korma", "curry", "in", 160, 4, 11, 11, "bowl=200", "bowl", "navrattan korma|veg korma|vegetable korma"),
    F("Dum aloo", "curry", "in", 130, 2, 14, 7.3, "bowl=150", "bowl", "kashmiri dum aloo|dum alu"),
    F("Avial", "vegetable", "in", 110, 2.5, 8, 7.5, "bowl=150", "bowl", "aviyal"),
    F("Vegetable thoran / poriyal", "vegetable", "in", 100, 2.5, 8, 6.5, "bowl=120", "bowl", "thoran|poriyal|palya|cabbage thoran"),
    F("Undhiyu", "vegetable", "in", 160, 4, 15, 9.5, "bowl=150", "bowl", "undhiyun|oondhiyu"),
    F("Pav bhaji", "fastfood", "in", 170, 4, 22, 7.3, "plate=300", "plate", "paav bhaji|pao bhaji|পাও ভাজি"),
    F("Gatte ki sabzi", "curry", "in", 150, 6, 13, 8.2, "bowl=150", "bowl", "gatta curry|besan gatte"),
    F("Mushroom masala", "curry", "sa", 90, 3, 6, 6, "bowl=150", "bowl", "mushroom curry|mushroom bhuna|মাশরুম ভুনা"),
    F("Polos curry (young jackfruit)", "curry", "lk", 120, 2, 14, 6.2, "bowl=150", "bowl", "polos|jackfruit curry"),
    F("Brinjal moju", "vegetable", "lk", 220, 1.5, 15, 17, "bowl=100", "bowl", "wambatu moju|eggplant moju|brinjal pickle"),
    F("Beetroot curry (Sri Lankan)", "vegetable", "lk", 90, 1.8, 9, 5.2, "bowl=150", "bowl", "beetroot curry|rathu ala"),
    F("Mallum", "leafy", "lk", 110, 3, 7, 7.8, "bowl=100", "bowl", "mallung|kola mallum|green mallum"),
    F("Aloo tama", "curry", "np", 90, 3.5, 11, 3.6, "bowl=200", "bowl", "alu tama|bamboo shoot curry"),
    F("Gundruk soup", "leafy", "np", 50, 2.5, 5, 2.2, "bowl=200", "bowl", "gundruk|gundruk ko jhol|gundruk sadeko"),

    # ---- Leafy greens (cooked with oil unless noted) --------------------------------------------
    F("Lal shak bhaji (red amaranth)", "leafy", "bd", 70, 3, 5, 4.3, "bowl=100", "bowl", "lal shak|laal saag|red amaranth|লাল শাক"),
    F("Pui shak (Malabar spinach)", "leafy", "bd", 55, 2, 4, 3.5, "bowl=150", "bowl", "pui shak|poi saag|basella|পুঁই শাক"),
    F("Kolmi shak (water spinach)", "leafy", "bd", 65, 2.8, 4.5, 4, "bowl=100", "bowl", "kolmi|kalmi saag|kangkong|কলমি শাক"),
    F("Pat shak (jute leaves)", "leafy", "bd", 75, 4, 7, 3.5, "bowl=100", "bowl", "pat shak|nalte shak|jute leaves|পাট শাক"),
    F("Data shak (amaranth stems)", "leafy", "bd", 60, 2.5, 5, 3.3, "bowl=100", "bowl", "data shak|notey shak|dantasag|ডাটা শাক|নটে শাক"),
    F("Lau shak (bottle gourd leaves)", "leafy", "bd", 55, 2.5, 4, 3.2, "bowl=100", "bowl", "lau shak|lau pata|লাউ শাক"),
    F("Mula shak (radish greens)", "leafy", "bd", 55, 2.4, 4.5, 3, "bowl=100", "bowl", "mula shak|mooli saag|মুলা শাক"),
    F("Helencha shak", "leafy", "bd", 60, 2.5, 4.5, 3.6, "bowl=100", "bowl", "hinche shak|helencha|হেলেঞ্চা শাক"),
    F("Moringa leaves bhaji (shojne pata)", "leafy", "bd", 110, 6, 7, 6.5, "bowl=100", "bowl", "sojne pata|moringa|drumstick leaves|সজনে পাতা"),
    T("Fenugreek leaves (methi), raw", "leafy", "in", 49, 4.4, 6, 0.9, "cup=40,handful=20", "handful", "methi|methi shak|মেথি শাক"),
    T("Mint leaves (pudina)", "leafy", "sa", 44, 3.3, 8.4, 0.7, "tbsp=3,handful=10", "handful", "pudina|pudina pata|mint|পুদিনা পাতা"),
    T("Coriander leaves", "leafy", "sa", 23, 2.1, 3.7, 0.5, "tbsp=4,handful=10", "handful", "dhonepata|dhonia pata|cilantro|dhania|ধনেপাতা"),

    # ---- Vegetables (raw unless noted) -----------------------------------------------------------
    T("Pointed gourd (potol)", "vegetable", "bd", 20, 2, 2.2, 0.3, "piece=40", "piece*3", "potol|parwal|patol|পটল"),
    T("Ridge gourd (jhinga)", "vegetable", "bd", 20, 1.2, 4.4, 0.2, "piece=150,cup=100", "cup", "jhinga|turai|tori|ঝিঙা"),
    T("Snake gourd (chichinga)", "vegetable", "bd", 18, 0.6, 3.8, 0.4, "piece=200,cup=100", "cup", "chichinga|chichinge|padwal|চিচিঙ্গা কাঁচা"),
    T("Ash gourd (chalkumra)", "vegetable", "bd", 13, 0.4, 3, 0.2, "cup=130", "cup", "chalkumra|petha|winter melon|চালকুমড়া"),
    T("Green banana (kacha kola)", "vegetable", "bd", 122, 1.3, 31.9, 0.4, "piece=180", "piece", "kacha kola|kanchkola|plantain|কাঁচা কলা"),
    T("Taro root (kochu), cooked", "vegetable", "bd", 142, 0.5, 34.6, 0.1, "cup=132,piece=50", "cup*0.5", "kochu|arbi|taro|কচু"),
    T("Elephant foot yam (ol)", "vegetable", "bd", 79, 1.2, 18.4, 0.1, "cup=130", "cup*0.5", "ol kochu|suran|jimikand|ওল"),
    T("Banana flower (mocha)", "vegetable", "bd", 34, 1.6, 5.1, 0.6, "cup=100", "cup", "mocha raw|kela phool|মোচা"),
    T("Drumstick pods (shojne data)", "vegetable", "bd", 37, 2.1, 8.5, 0.2, "piece=20,cup=100", "piece*3", "sojne|moringa pods|sahjan|সজনে"),
    T("Green papaya", "vegetable", "bd", 27, 0.7, 5.7, 0.2, "cup=140", "cup", "kacha pepe|raw papaya|কাঁচা পেঁপে"),
    T("Yardlong beans (borboti)", "vegetable", "bd", 47, 2.8, 8.4, 0.4, "cup=90,handful=50", "cup", "borboti|chawli phalli|yard long bean|বরবটি"),
    T("Hyacinth / flat beans (shim)", "vegetable", "bd", 48, 3.8, 6.7, 0.7, "cup=90,handful=50", "cup", "shim|sem|papdi|শিম"),
    T("Turnip (shalgom)", "vegetable", None, 28, 0.9, 6.4, 0.1, "piece=120,cup=130", "cup", "shalgom|shalgam|শালগম"),
    T("Kohlrabi (olkopi)", "vegetable", "bd", 27, 1.7, 6.2, 0.1, "piece=150,cup=135", "cup", "olkopi|ganth gobhi|ওলকপি"),
    T("Lotus stem", "vegetable", "in", 74, 2.6, 17.2, 0.1, "cup=120", "cup*0.5", "kamal kakdi|bhein|nadru|shaluk|শালুক"),
    T("Spring onion (peyajkoli)", "vegetable", "bd", 32, 1.8, 7.3, 0.2, "cup=100,piece=15", "piece*3", "peyajkoli|piyajkoli|hara pyaz|scallion|পেঁয়াজকলি"),
    T("Jackfruit seeds, boiled", "vegetable", "bd", 133, 6.6, 25.8, 0.4, "piece=6,handful=40", "handful", "kathal bichi|kathaler bichi|কাঁঠালের বিচি"),

    # ---- Fish -----------------------------------------------------------------------------------
    T("Hilsa, raw", "fish", "bd", 270, 21.8, 0, 19.4, "piece=100", "piece", "ilish raw|kacha ilish|কাঁচা ইলিশ"),
    F("Hilsa paturi", "fish", "bd", 260, 18, 3, 19.5, "piece=120", "piece", "ilish paturi|ইলিশ পাতুরি"),
    F("Hilsa bhapa (steamed in mustard)", "fish", "bd", 250, 17.5, 3, 18.8, "piece=120", "piece", "ilish bhapa|bhapa ilish|ভাপা ইলিশ"),
    F("Rui fish fry", "fish", "bd", 200, 20, 2, 12.5, "piece=80", "piece", "rui mach bhaja|rohu fry|রুই মাছ ভাজা"),
    F("Rui kalia", "curry", "bd", 170, 15, 5, 10, "piece=120", "piece", "rui kaliya|macher kalia|রুই মাছের কালিয়া"),
    F("Pangas bhuna", "curry", "bd", 170, 13, 3, 11.8, "piece=100,bowl=150", "piece", "pangas mach bhuna|pangash curry|পাঙ্গাস মাছ ভুনা"),
    F("Tilapia fry", "fish", "bd", 190, 22, 3, 10, "piece=100", "piece", "telapia bhaja|tilapia bhaja|তেলাপিয়া ভাজা"),
    F("Tilapia curry", "curry", "bd", 125, 14, 3, 6.3, "piece=110", "piece", "telapia jhol|tilapia bhuna|তেলাপিয়া মাছের তরকারি"),
    F("Koi fish fry", "fish", "bd", 230, 19, 2, 16.3, "piece=60", "piece*2", "koi mach bhaja|climbing perch|কই মাছ ভাজা"),
    F("Tel koi (koi curry)", "curry", "bd", 180, 15, 4, 11.5, "piece=90", "piece", "koi mach|koi bhuna|তেল কই|কই মাছ"),
    F("Shing fish curry", "curry", "bd", 115, 15, 3, 4.8, "piece=50,bowl=150", "bowl", "shing mach|singi|stinging catfish|শিং মাছের ঝোল"),
    F("Magur fish curry", "curry", "bd", 125, 14, 3, 6.3, "piece=60,bowl=150", "bowl", "magur mach|walking catfish|মাগুর মাছ"),
    F("Pabda fish curry", "curry", "bd", 140, 14, 3, 8, "piece=60", "piece*2", "pabda mach|pabda jhol|পাবদা মাছ"),
    F("Tengra fish curry", "curry", "bd", 135, 14, 3, 7.5, "bowl=150", "bowl", "tengra mach|tangra|টেংরা মাছ"),
    F("Boal fish curry", "curry", "bd", 150, 14, 3, 9.2, "piece=100", "piece", "boal mach|boal bhuna|বোয়াল মাছ"),
    F("Aair fish curry", "curry", "bd", 145, 15, 3, 8.1, "piece=100", "piece", "air mach|ayre|আইড় মাছ"),
    F("Shol fish curry", "curry", "bd", 130, 16, 3, 6, "piece=100", "piece", "shol mach|snakehead|শোল মাছ"),
    F("Kachki fish chorchori", "curry", "bd", 140, 14, 4, 7.6, "bowl=120", "bowl", "kachki mach|kachki chorchori|কাচকি মাছের চচ্চড়ি"),
    F("Puti fish fry", "fish", "bd", 220, 18, 3, 15, "piece=15", "piece*4", "puti mach bhaja|punti|পুঁটি মাছ ভাজা"),
    F("Chingri malaikari", "curry", "bd", 190, 12, 5, 13.5, "bowl=150,piece=40", "bowl", "prawn malai curry|malai chingri|চিংড়ি মালাইকারি"),
    F("Golda chingri bhuna (giant prawn)", "curry", "bd", 160, 15, 4, 9.3, "piece=60", "piece*2", "golda chingri|lobster curry|গলদা চিংড়ি"),
    F("Prawn fry (batter)", "fish", "bd", 250, 15, 15, 14.5, "piece=20", "piece*4", "chingri fry|chingri bhaja|fried prawn|চিংড়ি ফ্রাই"),
    F("Loitta fry (Bombay duck)", "fish", "bd", 260, 13, 14, 17, "piece=30", "piece*3", "loitta mach bhaja|bombil fry|লইট্টা ফ্রাই"),
    F("Rupchanda fry (pomfret)", "fish", "bd", 220, 19, 5, 13.5, "piece=120", "piece", "rupchanda bhaja|pomfret fry|রূপচাঁদা ভাজা"),
    F("Koral / bhetki fish curry", "curry", "bd", 125, 15, 3, 5.8, "piece=100", "piece", "koral mach|bhetki|sea bass curry|কোরাল মাছ|ভেটকি"),
    F("Fish fry (crumbed, Kolkata style)", "fish", "sa", 240, 14, 16, 13.5, "piece=90", "piece", "bhetki fish fry|fish fry|ফিশ ফ্রাই"),
    F("Fish kofta curry", "curry", "bd", 170, 11, 8, 10.5, "piece=40,bowl=150", "bowl", "macher kofta|fish ball curry|মাছের কোফতা"),
    F("Muri ghonto (fish head with rice)", "curry", "bd", 170, 9, 14, 8.8, "bowl=150", "bowl", "muriganto|macher matha|মুড়িঘণ্ট"),
    F("Fish roe fry (macher dim)", "fish", "bd", 230, 17, 6, 15.5, "piece=40", "piece*2", "macher dim bhaja|fish egg fry|মাছের ডিম ভাজা"),
    F("Shutki bhuna (dried fish curry)", "curry", "bd", 250, 30, 6, 12, "bowl=80", "bowl", "loitta shutki|shutki torkari|chingri shutki|শুঁটকি ভুনা|শুঁটকি"),
    T("Dried fish (shutki), raw", "fish", "bd", 300, 65, 0, 4, "piece=10,handful=30", "handful", "shutki mach|sukhi machli|dry fish|শুঁটকি মাছ"),
    F("Crab curry (kakra)", "curry", "bd", 110, 13, 4, 4.8, "bowl=150,piece=100", "bowl", "kakra bhuna|kekda|কাঁকড়া ভুনা"),
    F("Lahori / Amritsari fish fry", "fish", "pk", 250, 17, 12, 15, "piece=60", "piece*2", "lahori fish|amritsari fish|fish pakora"),
    F("Kerala fish curry", "curry", "in", 130, 13, 4, 7, "bowl=150", "bowl", "meen curry|fish molee|fish moilee"),
    F("Goan fish curry", "curry", "in", 140, 12, 4, 8.5, "bowl=150", "bowl", "goan curry|xitti kodi|fish curry rice"),
    F("Ambul thiyal (sour fish curry)", "curry", "lk", 160, 22, 3, 6.8, "piece=80", "piece*2", "ambul thiyal|fish ambul thiyal|sour fish"),
    F("Sri Lankan fish curry", "curry", "lk", 140, 14, 4, 7.6, "bowl=150", "bowl", "malu curry|fish curry coconut"),
    F("Fish cutlet", "fish", "sa", 230, 11, 20, 11.8, "piece=40", "piece*2", "fish chop|macher chop|ফিশ কাটলেট|মাছের চপ"),
    F("Masor tenga (Assamese sour fish)", "curry", "in", 80, 10, 3, 3, "bowl=200", "bowl", "masor tenga|tenga|sour fish curry"),

    # ---- Poultry --------------------------------------------------------------------------------
    F("Chicken rezala", "curry", "bd", 180, 14, 4, 12, "bowl=200,piece=90", "bowl", "murgir rezala|chicken rejala|মুরগির রেজালা"),
    F("Chicken korma (shahi)", "curry", "bd", 200, 14, 6, 13.5, "bowl=200,piece=90", "bowl", "murgir korma|shahi korma|chicken qorma|মুরগির কোরমা"),
    F("Chicken jhal fry", "poultry", "bd", 190, 20, 5, 10, "bowl=150", "bowl", "chicken jhalfry|chicken dry fry|চিকেন ঝাল ফ্রাই"),
    F("Butter chicken", "curry", "in", 180, 13, 6, 11.5, "bowl=200", "bowl", "murgh makhani|chicken makhani|বাটার চিকেন"),
    F("Chicken tikka masala", "curry", "in", 160, 13, 6, 9.5, "bowl=200", "bowl", "tikka masala|চিকেন টিক্কা মাসালা"),
    F("Tandoori chicken", "poultry", "sa", 165, 24, 3, 6.5, "piece=150", "piece", "tandoori murgh|তন্দুরি চিকেন"),
    F("Chicken 65", "poultry", "in", 250, 20, 10, 14.5, "serving=150,piece=25", "serving", "chicken sixty five|chicken 65 fry"),
    F("Chilli chicken", "poultry", "sa", 200, 15, 10, 11, "bowl=150", "bowl", "chili chicken|chicken chilli|চিলি চিকেন"),
    F("Chicken do pyaza", "curry", "sa", 160, 14, 6, 9, "bowl=200", "bowl", "chicken dopiaza|murgh do pyaza|চিকেন দোপেঁয়াজা"),
    F("Chicken Chettinad", "curry", "in", 175, 15, 5, 10.5, "bowl=200", "bowl", "chettinad chicken|kozhi chettinad"),
    F("Chicken karahi", "curry", "pk", 190, 16, 4, 12.3, "bowl=200", "bowl", "chicken kadai|kadai chicken|karahi|চিকেন কড়াই"),
    F("Chicken jalfrezi", "curry", "sa", 140, 14, 6, 6.8, "bowl=200", "bowl", "jalfrezi|চিকেন জালফ্রেজি"),
    F("Chicken vindaloo", "curry", "in", 170, 15, 5, 10, "bowl=200", "bowl", "vindaloo|vindalho"),
    F("Chicken sajji", "poultry", "pk", 190, 25, 1, 9.5, "piece=250,serving=200", "serving", "sajji|balochi sajji"),
    F("Chicken handi", "curry", "pk", 190, 15, 5, 12.2, "bowl=200", "bowl", "handi chicken|murgh handi"),
    F("Chicken reshmi kebab", "poultry", "sa", 200, 20, 4, 11.5, "piece=40", "piece*3", "reshmi kabab|resmi kebab|রেশমি কাবাব"),
    F("Chicken malai tikka", "poultry", "sa", 210, 20, 3, 13, "piece=35", "piece*4", "malai kebab|murgh malai tikka|মালাই টিক্কা"),
    F("Chicken shashlik", "poultry", "bd", 150, 15, 8, 6.4, "piece=120", "piece", "shashlick|chicken skewer|শাশলিক"),
    F("Chicken cutlet", "poultry", "bd", 240, 15, 15, 13.5, "piece=80", "piece", "chicken katlet|crumbed chicken|চিকেন কাটলেট"),
    F("Chicken lollipop", "poultry", "sa", 260, 17, 10, 17, "piece=45", "piece*3", "lollipop chicken|drums of heaven|চিকেন ললিপপ"),
    F("Chicken chaap", "poultry", "bd", 250, 20, 6, 16.3, "piece=150", "piece", "chicken chap|চিকেন চাপ"),
    F("Duck curry (haser mangsho)", "curry", "bd", 240, 15, 3, 18.8, "bowl=150,piece=60", "bowl", "hasher mangsho bhuna|duck bhuna|হাঁসের মাংস ভুনা"),
    F("Pigeon curry (kobutor)", "curry", "bd", 180, 18, 3, 10.7, "bowl=150", "bowl", "kobutorer mangsho|pigeon bhuna|কবুতরের মাংস"),
    F("Devilled chicken", "poultry", "lk", 200, 16, 9, 11, "bowl=150", "bowl", "chicken devil|devilled chicken"),
    F("Sri Lankan chicken curry", "curry", "lk", 165, 14, 4, 10.4, "bowl=200", "bowl", "kukul mas curry|chicken curry coconut"),
    F("Chicken choila", "poultry", "np", 170, 20, 3, 8.7, "serving=150", "serving", "choila|chwela"),
    F("Chicken sekuwa", "poultry", "np", 180, 24, 3, 8, "serving=150,piece=25", "serving", "sekuwa|chicken bbq nepali"),
    F("Thai soup (restaurant)", "other", "bd", 60, 4, 6, 2.2, "bowl=250", "bowl", "thai soup|chicken thai soup|থাই স্যুপ"),
    F("Chicken corn soup", "other", "sa", 55, 3.5, 6.5, 1.6, "bowl=250", "bowl", "corn soup|chicken corn|কর্ন স্যুপ"),
    F("Hot and sour soup", "other", "sa", 45, 2.5, 5, 1.7, "bowl=250", "bowl", "hot n sour soup|হট অ্যান্ড সাওয়ার স্যুপ"),

    # ---- Beef, mutton, other meat -----------------------------------------------------------------
    F("Beef kala bhuna", "curry", "bd", 260, 22, 4, 17.5, "bowl=150,piece=35", "bowl", "kala bhuna|chittagong kala bhuna|কালা ভুনা"),
    F("Mezbani beef", "curry", "bd", 210, 17, 4, 14, "bowl=200,piece=40", "bowl", "mezban|mejbani mangsho|মেজবানি মাংস"),
    F("Beef rezala", "curry", "bd", 210, 16, 5, 14, "bowl=200", "bowl", "gorur rezala|beef rejala|গরুর রেজালা"),
    F("Keema curry", "curry", "sa", 220, 16, 5, 15.3, "bowl=150", "bowl", "kima bhuna|qeema|keema masala|কিমা ভুনা"),
    F("Beef jhal fry", "curry", "bd", 230, 22, 5, 13.5, "bowl=150", "bowl", "gorur jhal fry|beef dry fry|বিফ ঝাল ফ্রাই"),
    F("Beef chaap", "meat", "bd", 280, 20, 8, 18.7, "piece=150", "piece", "beef chap|gorur chap|বিফ চাপ"),
    F("Boti kebab", "meat", "sa", 220, 24, 3, 12.5, "piece=25", "piece*4", "boti kabab|tikka boti|বটি কাবাব"),
    F("Sutli kebab", "meat", "bd", 250, 18, 5, 17.5, "piece=60", "piece*2", "sutli kabab|puran dhaka kebab|সুতলি কাবাব"),
    F("Jali kebab", "meat", "bd", 260, 15, 10, 17.8, "piece=50", "piece*2", "jali kabab|জালি কাবাব"),
    F("Chapli kebab", "meat", "pk", 280, 16, 8, 20.5, "piece=100", "piece", "chapli kabab|peshawari kebab|চাপলি কাবাব"),
    F("Galouti kebab", "meat", "in", 280, 15, 6, 21.8, "piece=40", "piece*2", "galawati kebab|tunde kebab"),
    F("Kofta curry (meatballs)", "curry", "sa", 200, 13, 6, 13.8, "bowl=150,piece=35", "bowl", "kofta|meatball curry|কোফতা"),
    F("Kolija bhuna (liver)", "curry", "bd", 190, 20, 6, 9.5, "bowl=120", "bowl", "kolija|kaleji|liver bhuna|কলিজা ভুনা"),
    F("Bot bhuna (tripe)", "curry", "bd", 160, 14, 3, 10.3, "bowl=120", "bowl", "bot|vuri|tripe curry|বট ভুনা|ভুঁড়ি"),
    F("Paya (trotter soup)", "curry", "sa", 110, 9, 2, 7.3, "bowl=250", "bowl", "paya|siri paye|nalli|পায়া"),
    F("Mutton rogan josh", "curry", "in", 190, 15, 4, 12.7, "bowl=200", "bowl", "rogan josh|roghan josh"),
    F("Mutton korma", "curry", "sa", 220, 15, 5, 15.7, "bowl=200", "bowl", "khasir korma|gosht korma|খাসির কোরমা"),
    F("Kosha mangsho (mutton)", "curry", "sa", 230, 17, 4, 16.2, "bowl=200", "bowl", "mutton kosha|kosha mangsho|কষা মাংস"),
    F("Keema matar", "curry", "in", 180, 13, 7, 11, "bowl=150", "bowl", "kheema mutter|keema peas"),
    F("Mutton karahi", "curry", "pk", 230, 17, 4, 16.2, "bowl=200", "bowl", "gosht karahi|shinwari karahi|মাটন কড়াই"),
    F("Bhuna gosht", "curry", "pk", 220, 17, 5, 14.7, "bowl=200", "bowl", "bhuna ghosht|gosht bhuna"),
    F("Aloo gosht", "curry", "sa", 150, 10, 8, 8.7, "bowl=200", "bowl", "alu gosht|alu diye mangsho|আলু গোশত|আলু দিয়ে মাংস"),
    F("Palak gosht", "curry", "pk", 150, 12, 4, 9.7, "bowl=200", "bowl", "saag gosht|palong mangsho"),
    F("Brain masala (mogoj)", "curry", "bd", 160, 10, 3, 12, "bowl=100", "bowl", "mogoj bhuna|bheja fry|মগজ ভুনা"),
    F("Black pork curry", "curry", "lk", 280, 16, 5, 22, "bowl=150", "bowl", "pork black curry|ooru mas"),
    F("Pork vindaloo", "curry", "in", 240, 16, 5, 17.3, "bowl=150", "bowl", "goan pork vindaloo"),
    F("Mutton sekuwa", "meat", "np", 220, 24, 2, 13, "serving=150", "serving", "khasi sekuwa|goat sekuwa"),
    F("Sukuti (dried meat)", "meat", "np", 350, 50, 5, 14, "serving=50", "serving", "sukuti sadeko|buff sukuti"),

    # ---- Eggs ------------------------------------------------------------------------------------
    T("Duck egg, boiled", "egg", "bd", 185, 12.8, 1.4, 13.8, "piece=70", "piece", "haser dim|hanser dim|হাঁসের ডিম"),
    T("Quail egg", "egg", "sa", 158, 13, 0.4, 11, "piece=9", "piece*4", "koel pakhir dim|kowel dim|কোয়েল পাখির ডিম"),
    F("Masala omelette", "egg", "bd", 190, 10.5, 3, 15.2, "piece=70", "piece", "piyaj morich omlet|deshi omelette|মসলা অমলেট"),
    F("Egg bhurji", "egg", "sa", 180, 11, 4, 13.3, "bowl=120", "bowl", "anda bhurji|dim jhuri|ডিম ঝুরি"),
    F("Egg korma", "curry", "bd", 170, 10, 5, 12.2, "piece=100", "piece", "dimer korma|anda korma|ডিমের কোরমা"),
    F("Egg devil (dimer devil)", "egg", "sa", 240, 10, 18, 14, "piece=70", "piece", "dimer devil|egg chop kolkata|ডিমের ডেভিল"),

    # ---- Dairy -----------------------------------------------------------------------------------
    T("Paneer", "dairy", "sa", 265, 18.3, 1.2, 20.8, "piece=20,cup=120", "piece*4", "panir|cottage cheese|পনির"),
    T("Chhana (fresh curd cheese)", "dairy", "bd", 200, 14, 4, 14.3, "cup=120,tbsp=15", "tbsp*4", "chana|channa|chhena|ছানা"),
    T("Khoa (mawa)", "dairy", "sa", 421, 14.6, 20.5, 31.2, "tbsp=15", "tbsp*2", "khoya|mawa|khir|ক্ষীর|খোয়া"),
    T("Milk cream (malai)", "dairy", "sa", 340, 2.8, 2.7, 36, "tbsp=15", "tbsp", "malai|shor|cream|মালাই|সর"),
    T("Buffalo milk", "dairy", "sa", 97, 3.8, 5.2, 6.9, "glass=250,cup=240", "glass", "mohisher dudh|bhains ka doodh|মহিষের দুধ", ml=1.03),
    T("Goat milk", "dairy", "sa", 69, 3.6, 4.5, 4.1, "glass=250,cup=240", "glass", "chagoler dudh|bakri ka doodh|ছাগলের দুধ", ml=1.03),
    F("Buttermilk (ghol / chaas)", "drink", "sa", 30, 1.5, 2.5, 1.5, "glass=250", "glass", "ghol|chaas|chhach|mattha|ঘোল|মাঠা", ml=1.03),
    F("Lassi, salted", "drink", "sa", 60, 3, 4.5, 3.3, "glass=250", "glass", "namkeen lassi|salty lassi|নোনতা লাচ্ছি", ml=1.04),
    F("Mango lassi", "drink", "sa", 105, 2.8, 18, 2.4, "glass=250", "glass", "aam lassi|ম্যাংগো লাচ্ছি", ml=1.05),
    F("Shrikhand", "dessert", "in", 250, 5, 38, 8.5, "bowl=100", "bowl", "srikhand|amrakhand"),
    F("Rabri", "dessert", "sa", 260, 7, 30, 12.5, "bowl=100", "bowl", "rabdi|rabadi|রাবড়ি"),
    F("Basundi", "dessert", "in", 220, 6, 28, 9.5, "bowl=120", "bowl", "basundi|basundi milk"),
    F("Kulfi", "dessert", "sa", 230, 6, 26, 11.5, "piece=70", "piece", "malai kulfi|kulfi malai|কুলফি"),
    F("Faluda", "dessert", "sa", 150, 3.5, 24, 4.5, "glass=300", "glass", "falooda|faluda ice cream|ফালুদা"),
    F("Juju dhau (king curd)", "dessert", "np", 140, 4, 17, 6.2, "bowl=150", "bowl", "juju dhau|bhaktapur dahi"),
    F("Rasmalai", "dessert", "sa", 190, 6, 24, 7.8, "piece=60", "piece*2", "roshmalai|ras malai|রসমালাই"),

    # ---- Sweets & desserts -----------------------------------------------------------------------
    F("Chomchom", "dessert", "bd", 320, 7, 56, 7.5, "piece=60", "piece", "chamcham|cham cham|porabari chomchom|চমচম"),
    F("Malai chomchom", "dessert", "bd", 340, 8, 52, 11, "piece=70", "piece", "malai chamcham|মালাই চমচম"),
    F("Pantua", "dessert", "sa", 320, 5, 48, 12, "piece=45", "piece*2", "ledikeni|lady kenny|পান্তুয়া|লেডিকেনি"),
    F("Rajbhog", "dessert", "sa", 200, 4.5, 40, 2.3, "piece=80", "piece", "raj bhog|boro roshogolla|রাজভোগ"),
    F("Kheer kadam", "dessert", "bd", 350, 8, 55, 11, "piece=50", "piece", "rasakadam|khirkodom|ক্ষীরকদম"),
    F("Kacha golla", "dessert", "bd", 290, 10, 42, 9, "piece=30", "piece*2", "kachagolla|natore kacha golla|কাঁচাগোল্লা"),
    F("Monda", "dessert", "bd", 360, 9, 58, 10.2, "piece=40", "piece*2", "muktagachar monda|monda mishti|মন্ডা"),
    F("Balish mishti", "dessert", "bd", 300, 6, 52, 7.5, "piece=150", "piece", "balish|gayanath balish|বালিশ মিষ্টি"),
    F("Nolen gurer sandesh", "dessert", "bd", 320, 8, 48, 10.5, "piece=30", "piece*2", "gurer sandesh|nolen gur|নলেন গুড়ের সন্দেশ"),
    F("Jilapi / jalebi", "dessert", "sa", 380, 3, 64, 12.5, "piece=30", "piece*2", "jilapi|jalebi|jilebi|জিলাপি"),
    F("Amriti / imarti", "dessert", "sa", 370, 5, 62, 11.5, "piece=35", "piece*2", "amriti|imarti|jangiri|আমৃত্তি"),
    F("Rasabali", "dessert", "in", 300, 7, 45, 10, "piece=50", "piece*2", "rasaballi|odia rasabali"),
    F("Chhena poda", "dessert", "in", 280, 9, 40, 9.3, "slice=80", "slice", "chenna poda|chhena pora|ছানা পোড়া"),
    F("Khaja", "dessert", "sa", 450, 5, 60, 21, "piece=30", "piece*2", "khaja mishti|খাজা"),
    F("Goja", "dessert", "bd", 430, 5, 62, 18, "piece=15", "piece*3", "gaja|গজা"),
    F("Batasha", "sweet", "sa", 390, 0, 97.5, 0, "piece=5", "piece*4", "batasa|patasha|বাতাসা"),
    F("Mihidana / boondi", "dessert", "sa", 420, 7, 58, 17.8, "serving=50,cup=100", "serving", "mihidana|bundiya|boondi|মিহিদানা|বুন্দিয়া"),
    F("Motichur laddu", "dessert", "sa", 420, 6, 57, 18.7, "piece=40", "piece", "laddu|ladoo|laddoo|boondi laddu|লাড্ডু|মতিচুর লাড্ডু"),
    F("Besan laddu", "dessert", "in", 470, 9, 52, 25, "piece=35", "piece", "besan ladoo|beshon laddu"),
    F("Narkel naru (coconut laddu)", "dessert", "bd", 420, 3.5, 50, 23, "piece=20", "piece*2", "narkel naru|narikel naru|coconut ladoo|নারকেলের নাড়ু"),
    F("Til naru (sesame laddu)", "dessert", "bd", 480, 12, 45, 28, "piece=20", "piece*2", "tiler naru|til ladoo|tilkut|তিলের নাড়ু"),
    F("Rava laddu", "dessert", "in", 430, 6, 60, 18.7, "piece=35", "piece", "suji laddu|rava ladoo"),
    F("Kaju katli", "dessert", "sa", 470, 9, 55, 24, "piece=12", "piece*3", "kaju barfi|cashew barfi|কাজু বরফি"),
    F("Barfi, milk", "dessert", "sa", 400, 10, 55, 15.5, "piece=30", "piece*2", "barfi|burfi|borfi|দুধের বরফি|বরফি"),
    F("Coconut barfi", "dessert", "sa", 430, 4, 55, 21.8, "piece=30", "piece*2", "narkel barfi|nariyal burfi|নারকেলের বরফি"),
    F("Soan papdi", "dessert", "sa", 500, 6, 60, 26, "piece=25", "piece*2", "sohan papdi|son papri|সোনপাপড়ি"),
    F("Mysore pak", "dessert", "in", 560, 6, 45, 40, "piece=30", "piece", "mysorepak"),
    F("Peda", "dessert", "sa", 400, 9, 60, 13.5, "piece=25", "piece*2", "pera|doodh peda|প্যাঁড়া"),
    F("Kalakand", "dessert", "sa", 350, 11, 45, 14.5, "piece=40", "piece", "kalakan|milk cake|কালাকাঁদ"),
    F("Sohan halwa", "dessert", "pk", 480, 6, 55, 26.5, "piece=30", "piece", "multani sohan halwa"),
    F("Gajar halwa", "dessert", "sa", 220, 4, 28, 10.5, "bowl=100", "bowl", "gajorer halua|gajar ka halwa|carrot halwa|গাজরের হালুয়া"),
    F("Suji halwa", "dessert", "sa", 330, 4.5, 45, 14.8, "bowl=100", "bowl", "halwa|halua|sooji halwa|sheera|সুজির হালুয়া|হালুয়া"),
    F("Chickpea halwa (boot halua)", "dessert", "bd", 380, 9, 50, 16.4, "piece=40", "piece*2", "buter halua|cholar daler halua|বুটের হালুয়া"),
    F("Egg halwa (dimer halua)", "dessert", "bd", 380, 9, 45, 18, "piece=40", "piece*2", "dimer halua|anda halwa|ডিমের হালুয়া"),
    F("Badam halwa", "dessert", "in", 500, 11, 45, 31, "bowl=60", "bowl", "almond halwa|badam halua"),
    F("Moong dal halwa", "dessert", "in", 420, 8, 45, 23, "bowl=80", "bowl", "mung dal halwa|muger halua"),
    F("Karachi halwa", "dessert", "in", 380, 1, 70, 10.7, "piece=30", "piece", "bombay halwa|corn flour halwa"),
    F("Firni", "dessert", "bd", 150, 4, 24, 4.2, "bowl=120", "bowl", "phirni|firni bati|ফিরনি"),
    F("Shahi tukra", "dessert", "sa", 330, 6, 40, 16, "piece=80", "piece", "shahi tukda|double ka meetha|শাহী টুকরা"),
    F("Jorda (sweet saffron rice)", "dessert", "sa", 250, 3, 45, 6.6, "cup=150,plate=200", "cup", "zarda|jarda|meethe chawal|জর্দা"),
    F("Custard", "dessert", "sa", 120, 3.5, 18, 3.8, "bowl=150", "bowl", "fruit custard|কাস্টার্ড"),
    F("Caramel pudding", "dessert", "bd", 150, 5, 22, 4.7, "slice=80", "slice", "pudding|egg pudding|caramel custard|পুডিং"),
    F("Patishapta pitha", "dessert", "bd", 250, 4.5, 38, 9, "piece=60", "piece*2", "patishapta|patisapta|পাটিসাপটা"),
    F("Pakan pitha", "dessert", "bd", 380, 4, 55, 16, "piece=40", "piece*2", "pakon pitha|পাকান পিঠা"),
    F("Teler pitha", "dessert", "bd", 350, 4, 55, 13, "piece=40", "piece*2", "tel pitha|gurer pitha|তেলের পিঠা"),
    F("Malpua", "dessert", "sa", 350, 5, 50, 14.5, "piece=50", "piece*2", "malpoa|maalpua|মালপোয়া"),
    F("Dudh puli pitha", "dessert", "bd", 180, 4, 30, 4.9, "bowl=150,piece=40", "bowl", "dudh puli|puli pitha|দুধ পুলি"),
    F("Bhapa pitha (with gur and coconut)", "dessert", "bd", 230, 3.5, 46, 3.6, "piece=80", "piece", "bhapa pitha|vapa pitha|ভাপা পিঠা"),
    F("Nokshi pitha", "dessert", "bd", 400, 4, 60, 16, "piece=30", "piece*2", "nakshi pitha|নকশি পিঠা"),
    F("Banana pitha (kola pitha)", "dessert", "bd", 300, 3, 45, 12, "piece=30", "piece*2", "kolar pitha|kola pitha|কলার পিঠা"),
    F("Taler pitha (palm fruit fritter)", "dessert", "bd", 320, 3.5, 45, 14, "piece=40", "piece*2", "tal pitha|taler bora|তালের পিঠা"),
    F("Chushi pitha", "dessert", "bd", 190, 4.5, 30, 5.8, "bowl=150", "bowl", "chusi pitha|চুষি পিঠা"),
    F("Muri moa", "sweet", "bd", 380, 5, 86, 1.3, "piece=30", "piece*2", "murir moa|moa|khoi moa|chirar moa|মুড়ির মোয়া|মোয়া"),
    F("Kesari bath / rava kesari", "dessert", "in", 300, 3.5, 45, 12, "bowl=100", "bowl", "kesari|rava kesari|sheera"),
    F("Payasam", "dessert", "in", 170, 4, 25, 6, "bowl=150", "bowl", "semiya payasam|paal payasam|kheer south"),
    F("Modak", "dessert", "in", 250, 3.5, 42, 7.8, "piece=40", "piece*2", "ukadiche modak|modakam"),
    F("Puran poli", "dessert", "in", 290, 7, 50, 7, "piece=80", "piece", "puranpoli|obbattu|holige"),
    F("Unniyappam", "dessert", "in", 320, 3, 50, 12, "piece=20", "piece*3", "unni appam|neyyappam"),
    F("Kavum (oil cake)", "dessert", "lk", 400, 4, 55, 18.4, "piece=40", "piece", "konda kavum|oil cake"),
    F("Kokis", "snack", "lk", 500, 6, 50, 31, "piece=10", "piece*3", "kokis sri lanka"),
    F("Watalappan", "dessert", "lk", 230, 6, 30, 10, "bowl=120", "bowl", "watalappam|vattalappam"),
    F("Yomari", "dessert", "np", 250, 4, 50, 3.5, "piece=60", "piece*2", "yomari punhi"),
    F("Sheer khurma", "dessert", "pk", 220, 5.5, 28, 9.8, "bowl=150", "bowl", "sheer korma|shir khurma|শির খুরমা"),
    F("Balushahi", "dessert", "in", 450, 4.5, 55, 23.7, "piece=40", "piece", "badusha|balushai"),
    F("Petha (ash gourd candy)", "dessert", "in", 330, 0.4, 82, 0.1, "piece=30", "piece*2", "agra petha|mohanbhog"),
    F("Ghevar", "dessert", "in", 450, 5, 55, 23.4, "piece=60", "piece", "ghewar"),
    F("Sitabhog", "dessert", "in", 340, 6, 60, 8.4, "serving=100", "serving", "sitabhog burdwan"),
    F("Chhena murki", "dessert", "sa", 380, 8, 65, 9.8, "serving=50", "serving", "chanar murki|ছানার মুড়কি"),
    F("Mango leather (aamshotto)", "sweet", "bd", 320, 1, 78, 0.6, "piece=20", "piece*2", "aamshotto|aam papad|amsotto|আমসত্ত্ব"),
    F("Mango pulp, sweetened (aamras)", "dessert", "in", 92, 0.7, 22, 0.3, "bowl=150", "bowl", "aam ras|mango pulp|আমের রস"),

    # ---- Snacks & street food --------------------------------------------------------------------
    F("Beguni", "snack", "bd", 280, 5, 25, 18, "piece=30", "piece*3", "begun bhaja besan|baingan pakora|বেগুনি"),
    F("Aloo chop", "snack", "bd", 250, 4.5, 30, 12.5, "piece=50", "piece*2", "alur chop|potato chop|আলুর চপ"),
    F("Vegetable chop / cutlet", "snack", "sa", 240, 4.5, 30, 11.5, "piece=50", "piece*2", "veg chop|veg cutlet|ভেজিটেবল চপ"),
    F("Egg chop (dim chop)", "snack", "bd", 230, 9, 16, 14.5, "piece=90", "piece", "dim chop|egg chop|ডিম চপ"),
    F("Chicken roll (paratha roll)", "fastfood", "sa", 260, 11, 26, 12.5, "piece=180", "piece", "kathi roll|chicken kathi|paratha roll|frankie|চিকেন রোল"),
    F("Egg paratha roll", "fastfood", "sa", 280, 8.5, 28, 15, "piece=160", "piece", "dim roll|anda roll|এগ রোল"),
    F("Spring roll", "snack", "sa", 250, 5, 28, 13, "piece=50", "piece*2", "vegetable roll|veg spring roll|chicken spring roll|স্প্রিং রোল"),
    F("Chicken shawarma", "fastfood", "bd", 220, 12, 22, 9.3, "piece=250", "piece", "shawarma|shorma|shwarma|শর্মা"),
    F("Chicken momo, steamed", "snack", "np", 200, 10, 24, 7, "piece=30", "piece*6", "momo|momos|dumpling|মোমো"),
    F("Veg momo, steamed", "snack", "np", 170, 5, 28, 4.2, "piece=28", "piece*6", "veg momos|vegetable momo"),
    F("Fried momo", "snack", "np", 280, 9, 26, 15.5, "piece=32", "piece*6", "kothey momo|fried momos"),
    F("Thukpa", "grain", "np", 80, 5, 11, 1.8, "bowl=350", "bowl", "thukpa noodle soup|thenthuk"),
    F("Chicken pakora", "snack", "sa", 260, 15, 14, 16, "piece=20", "piece*4", "chicken pakoda|chicken fry pakora|চিকেন পাকোড়া"),
    F("Paneer pakora", "snack", "in", 300, 11, 16, 21.5, "piece=30", "piece*3", "paneer pakoda"),
    F("Bread pakora", "snack", "in", 280, 6.5, 30, 15, "piece=70", "piece", "bread pakoda"),
    F("Dhokla", "snack", "in", 160, 6, 22, 5.3, "piece=30", "piece*3", "khaman|khaman dhokla|ধোকলা"),
    F("Khandvi", "snack", "in", 190, 7, 20, 9, "piece=15", "piece*5", "patuli|suralichi vadi"),
    F("Kachori (khasta)", "snack", "in", 420, 8, 45, 23, "piece=45", "piece*2", "khasta kachori|pyaz kachori|dal kachori"),
    F("Vada pav", "fastfood", "in", 290, 7, 40, 11.3, "piece=140", "piece", "wada pav|batata vada pav"),
    F("Medu vada", "snack", "in", 300, 10, 28, 16.5, "piece=45", "piece*2", "medu wada|ulundu vadai|uzhunnu vada"),
    F("Masala vada / parippu vadai", "snack", "sa", 320, 13, 30, 16.5, "piece=35", "piece*2", "parippu vadai|dal vada|masal vadai|chana dal vada|মসলা বড়া"),
    F("Isso vadai (prawn vadai)", "snack", "lk", 300, 14, 26, 15.5, "piece=50", "piece*2", "isso wade|prawn vade"),
    F("Aloo bonda / batata vada", "snack", "in", 250, 5, 30, 12.2, "piece=50", "piece*2", "bonda|batata vada|alur bora"),
    F("Dahi puri (doi fuchka)", "snack", "sa", 170, 4.5, 25, 5.7, "piece=25", "piece*6", "dahi puri|doi fuchka|দই ফুচকা"),
    F("Sev puri", "snack", "in", 280, 6, 35, 13, "plate=150", "plate", "sev poori"),
    F("Bhel puri", "snack", "in", 200, 5, 32, 6, "plate=150", "plate", "bhelpuri|bhel|velpuri|ভেলপুরি"),
    F("Papdi chaat", "snack", "in", 210, 6, 28, 8.4, "plate=200", "plate", "papri chaat|chaat"),
    F("Aloo tikki", "snack", "in", 200, 3.5, 26, 9.3, "piece=60", "piece*2", "alu tikki|aloo tikki chaat"),
    F("Samosa chaat", "snack", "in", 190, 5.5, 24, 8.3, "plate=250", "plate", "samosa chaat|সমুচা চাট"),
    F("Dahi vada / doi bora", "snack", "sa", 160, 6, 18, 7.1, "piece=80", "piece*2", "dahi bhalla|dahi baray|doi bora|দই বড়া"),
    F("Misal pav", "snack", "in", 170, 6.5, 22, 6.4, "plate=350", "plate", "misal|misal pao"),
    F("Poha (kanda poha)", "snack", "in", 160, 3, 26, 5, "plate=200", "plate", "kanda poha|batata poha|chirer pulao|চিড়ার পোলাও"),
    F("Chire bhaja (fried flattened rice)", "snack", "bd", 460, 8, 60, 21, "handful=30,cup=50", "handful", "chira bhaja|poha chivda|chivda|চিড়া ভাজা"),
    F("Upma", "snack", "in", 150, 3.5, 22, 5.3, "plate=200", "plate", "uppittu|rava upma|উপমা"),
    F("Nimki", "snack", "bd", 500, 8, 55, 27.5, "handful=30,piece=5", "handful", "nimki|namak pare|নিমকি"),
    F("Sev / bhujia", "snack", "sa", 560, 15, 42, 37, "handful=30", "handful", "bhujia|aloo bhujia|jhuri bhaja|ঝুরি ভাজা"),
    F("Mathri", "snack", "in", 500, 8, 52, 29, "piece=15", "piece*3", "mathi|mathiya"),
    F("Khakhra", "snack", "in", 420, 12, 62, 13.5, "piece=20", "piece*2", "khakra|methi khakhra"),
    F("Murukku / chakli", "snack", "in", 520, 8, 55, 30, "piece=15", "piece*3", "murukku|chakli|chakri"),
    T("Banana chips", "snack", "in", 519, 2.3, 58.4, 33.6, "handful=30", "handful", "kela chips|nendran chips|কলার চিপস"),
    F("Papad, roasted", "snack", "sa", 370, 25.6, 59.9, 3.3, "piece=12", "piece*2", "papadum|pappadam|papor|পাঁপড় পোড়া"),
    F("Papad, fried", "snack", "sa", 450, 20, 48, 20, "piece=14", "piece*2", "fried papad|papor bhaja|পাঁপড় ভাজা"),
    F("Chicken samosa (mini)", "snack", "bd", 290, 10, 30, 14.5, "piece=30", "piece*3", "chicken samucha|keema samosa|kima somucha|চিকেন সমুচা"),
    F("Liver singara (kolija singara)", "snack", "bd", 290, 8, 32, 14.5, "piece=50", "piece*2", "kolija singara|koliza shingara|কলিজা সিঙ্গারা"),
    F("Chicken patties (puff)", "snack", "bd", 330, 8, 30, 20, "piece=80", "piece", "chicken patis|chicken puff|chicken pattice|চিকেন প্যাটিস"),
    F("Vegetable patties (puff)", "snack", "bd", 320, 5, 32, 19, "piece=70", "piece", "veg patis|veg puff|ভেজিটেবল প্যাটিস"),
    F("Chicken sandwich (bakery)", "fastfood", "bd", 250, 11, 28, 10.5, "piece=120", "piece", "club sandwich|chicken sandwich|স্যান্ডউইচ"),
    F("Fish bun / fish roll", "snack", "lk", 270, 10, 30, 12.4, "piece=80", "piece", "fish bun|fish roll|chinese roll"),
    F("Chana chaat", "snack", "sa", 130, 6, 18, 3.8, "bowl=150", "bowl", "chola chaat|chickpea chaat|ছোলা চাট"),
    F("Fruit chaat", "fruit", "sa", 70, 0.8, 16, 0.3, "bowl=200", "bowl", "fruit salad|ফ্রুট চাট"),
    F("Bun kebab (burger)", "fastfood", "pk", 250, 10, 28, 11, "piece=150", "piece", "bun kabab|anda shami burger"),
    T("Makhana (fox nuts), roasted", "nuts", "in", 350, 9.7, 77, 0.1, "cup=32,handful=10", "cup", "makhana|phool makhana|fox nut|lotus seeds|মাখনা"),
    F("Instant noodles, cooked", "packaged", "bd", 150, 3, 19, 6.8, "serving=250,bowl=250", "serving", "maggi|mr noodles|cooked noodles|masala noodles|রান্না নুডলস"),
    F("Chicken pizza", "pizza", None, 260, 12, 28, 11, "slice=110", "slice*2", "chicken tikka pizza|bbq chicken pizza|চিকেন পিজা"),

    # ---- Drinks -----------------------------------------------------------------------------------
    F("Masala chai", "hotdrink", "sa", 70, 2, 10, 2.4, "cup=150", "cup", "masala tea|ada cha dudh|মসলা চা", ml=1.03),
    F("Condensed-milk tea (tong cha)", "hotdrink", "bd", 90, 2, 15, 2.4, "cup=100", "cup", "tong er cha|condensed milk cha|malai cha|কনডেন্সড মিল্ক চা|মালাই চা", ml=1.04),
    F("Lemon / ginger tea with sugar", "hotdrink", "bd", 25, 0, 6.3, 0, "cup=150", "cup", "lebu cha|ada cha|ginger tea|lemon tea|লেবু চা|আদা চা", ml=1.01),
    T("Green tea", "hotdrink", None, 1, 0.2, 0, 0, "cup=200", "cup", "green tea|সবুজ চা|গ্রিন টি", ml=1.0),
    F("Cold coffee", "drink", "sa", 90, 3, 13, 3, "glass=250", "glass", "iced coffee|কোল্ড কফি", ml=1.04),
    F("Kashmiri noon chai (pink tea)", "hotdrink", "pk", 90, 3, 10, 4.3, "cup=180", "cup", "noon chai|pink chai|sheer chai|kashmiri chai", ml=1.03),
    F("Doodh patti chai", "hotdrink", "pk", 85, 3, 11, 3.3, "cup=180", "cup", "doodh patti|dudh pati|milk tea strong", ml=1.03),
    F("Kahwa", "hotdrink", "pk", 20, 0.2, 5, 0, "cup=150", "cup", "kehwa|qahwa|green tea kahwa", ml=1.0),
    F("Lemon sherbet (lebur shorbot)", "drink", "sa", 30, 0.1, 7.5, 0, "glass=250", "glass", "lebur shorbot|nimbu pani|lemonade|shikanji|লেবুর শরবত", ml=1.02),
    F("Rooh Afza sherbet", "drink", "sa", 40, 0, 10, 0, "glass=250", "glass", "rooh afza|ruh afza|rose sherbet|রুহ আফজা", ml=1.02),
    F("Basil seed sherbet (tokma)", "drink", "bd", 45, 0.3, 11, 0.1, "glass=250", "glass", "tokma|sabja|isabgul shorbot|তোকমার শরবত|ইসবগুলের শরবত", ml=1.02),
    F("Bel sherbet (wood apple)", "drink", "bd", 70, 0.8, 16.5, 0.1, "glass=250", "glass", "beler shorbot|bael sharbat|বেলের শরবত", ml=1.04),
    F("Green mango drink (aam panna)", "drink", "sa", 55, 0.2, 13.5, 0, "glass=250", "glass", "kacha aamer shorbot|aam jhora|কাঁচা আমের শরবত", ml=1.03),
    F("Tamarind sherbet", "drink", "bd", 60, 0.2, 14.7, 0.1, "glass=250", "glass", "tetuler shorbot|imli sharbat|তেঁতুলের শরবত", ml=1.03),
    F("Jaljeera", "drink", "in", 25, 0.2, 6, 0, "glass=250", "glass", "jal jeera|jaljira", ml=1.01),
    F("Sattu drink", "drink", "in", 45, 2.2, 7, 0.6, "glass=300", "glass", "sattu sharbat|sattu ghol", ml=1.03),
    F("Badam milk", "drink", "sa", 110, 3.5, 13, 5, "glass=250", "glass", "almond milk drink|badam doodh|বাদাম দুধ", ml=1.04),
    F("Thandai", "drink", "in", 130, 3.5, 16, 5.8, "glass=250", "glass", "sardai", ml=1.04),
    F("Mango milkshake", "drink", "sa", 100, 2.8, 16, 2.8, "glass=300", "glass", "aam shake|mango shake|ম্যাংগো শেক", ml=1.05),
    F("Banana milkshake", "drink", "sa", 95, 3, 15, 2.6, "glass=300", "glass", "kola shake|banana shake|বানানা শেক", ml=1.05),
    F("Malted milk drink (with milk)", "hotdrink", "sa", 87, 3.5, 12.5, 2.6, "cup=200,glass=250", "cup", "horlicks|boost|bournvita|malt drink|হরলিক্স", ml=1.04),
    T("King coconut water (thambili)", "drink", "lk", 20, 0.1, 4.8, 0.1, "glass=300", "glass", "thambili|king coconut", ml=1.02),
    F("Mango drink (packaged)", "packaged", "sa", 60, 0, 15, 0, "piece=250,glass=250", "piece", "frooto|maaza|mango juice|ম্যাংগো জুস", ml=1.05),
    T("Coconut milk", "other", "sa", 200, 2, 2.8, 21.3, "tbsp=15,cup=226", "tbsp*2", "narkel dudh|nariyal doodh|নারকেলের দুধ"),

    # ---- Fruits -----------------------------------------------------------------------------------
    T("Mango, Himsagar", "fruit", "bd", 65, 0.8, 15.5, 0.4, "piece=200,cup=165", "piece", "himsagar|khirsapat|khirshapati|হিমসাগর আম"),
    T("Mango, Langra", "fruit", "bd", 65, 0.8, 15.5, 0.4, "piece=220,cup=165", "piece", "langra|langda aam|ল্যাংড়া আম"),
    T("Mango, Fazli", "fruit", "bd", 60, 0.7, 14.5, 0.3, "piece=400,cup=165", "piece*0.5", "fazli|fojli|ফজলি আম"),
    T("Mango, Amrapali", "fruit", "bd", 70, 0.8, 17, 0.4, "piece=150,cup=165", "piece", "amrapali|amropali|আম্রপালি আম"),
    T("Green mango (kacha aam)", "fruit", "bd", 44, 0.7, 10.1, 0.1, "piece=150", "piece*0.5", "kacha aam|kaccha aam|raw mango|kairi|কাঁচা আম"),
    T("Jamun (black plum)", "fruit", "bd", 60, 0.7, 15.6, 0.2, "piece=5,cup=135", "cup*0.5", "kalo jam|jam|java plum|jambul|জাম|কালোজাম ফল"),
    T("Hog plum (amra)", "fruit", "bd", 48, 0.7, 10.5, 0.3, "piece=40", "piece*2", "amra|amda|ambarella|আমড়া"),
    T("Bael (bel)", "fruit", "bd", 137, 1.8, 31.8, 0.3, "cup=150", "cup*0.5", "bel|bael|stone apple|বেল"),
    T("Wood apple (kodbel)", "fruit", "bd", 134, 7.1, 18.1, 3.7, "piece=100", "piece*0.5", "kodbel|kotbel|kaith|কদবেল"),
    T("Indian gooseberry (amloki)", "fruit", "bd", 44, 0.9, 10.2, 0.6, "piece=20", "piece*2", "amloki|amla|awla|আমলকি"),
    T("Jujube (boroi / ber)", "fruit", "bd", 79, 1.2, 20.2, 0.2, "piece=15,cup=100", "piece*5", "boroi|kul|ber|বরই|কুল"),
    T("Tamarind pulp (tetul)", "fruit", "bd", 239, 2.8, 62.5, 0.6, "tbsp=15", "tbsp", "tetul|imli|তেঁতুল"),
    T("Wax apple (jamrul)", "fruit", "bd", 25, 0.6, 5.7, 0.3, "piece=40", "piece*3", "jamrul|wax jambu|rose apple|জামরুল"),
    T("Custard apple (ata)", "fruit", "bd", 94, 2.1, 23.6, 0.3, "piece=100", "piece", "ata|sharifa|sitaphal|আতা"),
    T("Ice apple (taler shash)", "fruit", "bd", 43, 0.8, 10.9, 0.1, "piece=40", "piece*2", "taler shash|tal shash|nungu|তালের শাঁস"),
    T("Muskmelon (bangi)", "fruit", "bd", 34, 0.8, 8.2, 0.2, "slice=100,cup=160", "slice*2", "bangi|kharbuja|cantaloupe|বাঙ্গি"),
    T("Longan (ashphol)", "fruit", "bd", 60, 1.3, 15.1, 0.1, "piece=3,cup=100", "cup", "ashphol|anshfal|আঁশফল"),
    T("Rambutan", "fruit", None, 68, 0.9, 16, 0.2, "piece=10", "piece*5", "rambutan|রাম্বুটান"),
    T("Dragon fruit", "fruit", None, 57, 0.4, 15.2, 0.1, "piece=300,cup=200", "cup", "pitaya|ড্রাগন ফল"),
    T("Fig, fresh", "fruit", None, 74, 0.8, 19.2, 0.3, "piece=50", "piece*2", "dumur|anjeer|ডুমুর"),
    T("Figs, dried", "fruit", None, 249, 3.3, 63.9, 0.9, "piece=8", "piece*3", "anjeer dry|dried anjir|শুকনো ডুমুর"),
    T("Raisins", "fruit", None, 299, 3.1, 79.2, 0.5, "tbsp=9,handful=30", "tbsp*2", "kishmish|kismis|kishmis|কিশমিশ"),
    T("Dried apricots", "fruit", None, 241, 3.4, 62.6, 0.5, "piece=7", "piece*4", "khubani|khurmani"),
    T("Pomelo (jambura)", "citrus", "bd", 38, 0.8, 9.6, 0, "cup=190", "cup", "jambura|batabi lebu|chakotra|জাম্বুরা|বাতাবি লেবু"),
    T("Sweet lime (mosambi)", "citrus", "sa", 43, 0.8, 9.3, 0.3, "piece=150", "piece", "mosambi|musambi|mousambi|মোসাম্বি"),
    T("Banana, small (champa / sabri)", "fruit", "bd", 89, 1.1, 22.8, 0.3, "piece=60", "piece*2", "champa kola|sabri kola|chini champa|চাঁপা কলা|সবরি কলা"),
    T("Water chestnut (paniphal)", "fruit", "bd", 97, 1.4, 23.9, 0.1, "piece=12,cup=124", "piece*5", "paniphal|singhara|panifol|পানিফল"),
    T("Coconut, desiccated", "nuts", None, 660, 6.9, 23.7, 64.5, "tbsp=5,cup=80", "tbsp*2", "narkel kora|dry coconut|nariyal burada|নারকেল কোরা"),

    # ---- Seeds & nuts -----------------------------------------------------------------------------
    T("Sesame seeds (til)", "nuts", "sa", 573, 17.7, 23.5, 49.7, "tbsp=9", "tbsp", "til|teel|তিল"),
    T("Flaxseed (tishi)", "nuts", "sa", 534, 18.3, 28.9, 42.2, "tbsp=10", "tbsp", "tishi|alsi|linseed|তিসি"),
    T("Pumpkin seeds", "nuts", None, 559, 30.2, 10.7, 49, "tbsp=9,handful=28", "tbsp*2", "kumrar bichi|pepitas|কুমড়ার বিচি"),
    T("Sunflower seeds", "nuts", None, 584, 20.8, 20, 51.5, "tbsp=9,handful=28", "tbsp*2", "surjomukhi bichi"),
    T("Poppy seeds (posto)", "nuts", "sa", 525, 18, 28.1, 41.6, "tbsp=9", "tbsp", "posto|khus khus|পোস্ত"),
    T("Pine nuts (chilgoza)", "nuts", "pk", 673, 13.7, 13.1, 68.4, "handful=28", "handful", "chilgoza|neoza|pine nut"),

    # ---- Oils & sweeteners ------------------------------------------------------------------------
    T("Coconut oil", "fat", None, 892, 0, 0, 99.1, "tbsp=13.6,tsp=4.5", "tbsp", "narkel tel|নারকেল তেল", ml=0.92),
    T("Rice bran oil", "fat", None, 884, 0, 0, 100, "tbsp=13.6,tsp=4.5", "tbsp", "rice bran|ধানের কুঁড়ার তেল", ml=0.92),
    T("Palm oil", "fat", None, 884, 0, 0, 100, "tbsp=13.6,tsp=4.5", "tbsp", "palmolein|palm tel|পাম তেল", ml=0.92),
    T("Sunflower oil", "fat", None, 884, 0, 0, 100, "tbsp=13.6,tsp=4.5", "tbsp", "surjomukhi tel|সূর্যমুখী তেল", ml=0.92),
    T("Sesame oil", "fat", None, 884, 0, 0, 100, "tbsp=13.6,tsp=4.5", "tbsp", "til tel|gingelly oil|তিলের তেল", ml=0.92),
    T("Vanaspati (dalda)", "fat", "sa", 884, 0, 0, 100, "tbsp=13,tsp=4.3", "tsp", "dalda|vegetable ghee|ডালডা"),
    T("Date palm jaggery (khejur gur)", "sweet", "bd", 382, 0.4, 95, 0.1, "tbsp=15,piece=40", "tbsp", "khejur gur|nolen gur|patali gur|খেজুর গুড়|পাটালি গুড়"),
    T("Rock sugar (mishri)", "sweet", "sa", 390, 0, 97.5, 0, "tsp=4,tbsp=12", "tsp*2", "mishri|michri|মিছরি"),
    T("Glucose powder", "sweet", None, 370, 0, 92.5, 0, "tbsp=10", "tbsp*2", "glucon d|glucose|গ্লুকোজ"),
    T("Tomato ketchup", "other", None, 101, 1, 27.4, 0.1, "tbsp=17", "tbsp", "ketchup|tomato sauce|টমেটো সস"),
    T("Mayonnaise", "other", None, 680, 1, 0.6, 75, "tbsp=14", "tbsp", "mayo|মেয়োনিজ"),

    # ---- Bakery & packaged --------------------------------------------------------------------------
    F("Toast biscuit (rusk)", "snack", "bd", 410, 10, 72, 9, "piece=12", "piece*2", "toast|rusk|cha toast|টোস্ট বিস্কুট"),
    F("Dry cake (bakery)", "snack", "bd", 440, 7, 68, 15.5, "piece=20", "piece*2", "dry cake|ড্রাই কেক"),
    F("Cream biscuit", "packaged", None, 490, 5.5, 68, 22, "piece=12", "piece*3", "cream cracker sandwich|ক্রিম বিস্কুট"),
    F("Glucose biscuit", "packaged", "sa", 450, 7, 76, 13.5, "piece=7", "piece*4", "parle g|energy biscuit|গ্লুকোজ বিস্কুট"),
    F("Cream pastry", "dessert", "bd", 370, 4.5, 45, 19.5, "piece=80", "piece", "pastry|pastri|পেস্ট্রি"),
]
