package dev.ytosko.neutrino.data.food

import dev.ytosko.neutrino.domain.Nutrition
import dev.ytosko.neutrino.domain.food.Food
import dev.ytosko.neutrino.domain.food.FoodCategory
import dev.ytosko.neutrino.domain.food.FoodRanking
import dev.ytosko.neutrino.domain.food.FoodSource
import dev.ytosko.neutrino.domain.food.FoodUnit
import dev.ytosko.neutrino.domain.food.Portion
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonPrimitive
import kotlinx.serialization.json.doubleOrNull

@Serializable
private data class CatalogEntry(
    val id: String,
    @SerialName("n") val name: String,
    @SerialName("k") val category: String,
    @SerialName("e") val kcal: Double,
    @SerialName("p") val protein: Double,
    @SerialName("c") val carbs: Double,
    @SerialName("f") val fat: Double,
    @SerialName("u") val units: Map<String, Double> = emptyMap(),
    @SerialName("a") val aliases: List<String> = emptyList(),
    @SerialName("d") val default: List<JsonPrimitive>? = null,
    @SerialName("ml") val density: Double? = null,
)

/**
 * The built-in food list (assets/foods.json, generated by tools/fooddb): common generic foods
 * from USDA FoodData Central plus Bangladeshi/South Asian dishes. Small enough to keep in memory.
 */
class FoodCatalog(private val loadJson: () -> String) {

    private val json = Json { ignoreUnknownKeys = true }

    val foods: List<Food> by lazy {
        json.decodeFromString<List<CatalogEntry>>(loadJson()).map { it.toFood() }
    }

    fun byId(id: String): Food? = foods.firstOrNull { it.id == id }

    /** Foods matching [query], best match first. */
    fun search(query: String, limit: Int = 30): List<Food> =
        foods.asSequence()
            .map { it to FoodRanking.matchScore(query, it.name, it.aliases) }
            .filter { it.second > 0 }
            .sortedWith(compareByDescending<Pair<Food, Int>> { it.second }.thenBy { it.first.name.length })
            .take(limit)
            .map { it.first }
            .toList()

    private fun CatalogEntry.toFood() = Food(
        id = id,
        name = name,
        category = FoodCategory.fromKey(category),
        per100g = Nutrition(calories = kcal, proteinG = protein, carbsG = carbs, fatG = fat),
        unitGrams = units.mapNotNull { (key, grams) -> FoodUnit.fromKey(key)?.let { it to grams } }.toMap(),
        density = density,
        aliases = aliases,
        defaultPortion = default?.let { d ->
            val unit = FoodUnit.fromKey(d.getOrNull(0)?.content)
            val quantity = d.getOrNull(1)?.doubleOrNull
            if (unit != null && quantity != null) Portion(quantity, unit) else null
        },
        source = FoodSource.Builtin,
    )
}
